export {
  addPhase,
  buildNextPhase,
  computeComplement,
  computeNetRevenue,
  getActivePhase,
  getAssociateAnnualIncomeNeedForYear,
  getAssociateRevenuePhaseForYear,
  getPhaseEndYear,
  hasAssociateAnnualIncomeNeedForYear,
  isRevenuePhaseV6,
  removePhase,
  sortPhases,
  updatePhase,
  type RevenuePhaseInput,
} from '@/engine/tresorerie/revenuePhases';
