import type { SettingsRegistryEntry } from './types';
import {
  completeSource,
  currentJsonb,
  ownerMemento,
  percentValidation,
  plannedValidation,
  scaleValidation,
  settingsDefault,
  sourceToComplete,
} from './entryHelpers';

export const SETTINGS_CORE_REGISTRY = [
  {
    family: 'impots',
    key: 'impots.ir.bareme',
    label: 'Barème progressif IR',
    description: 'Tranches et taux du barème IR courant, consommés par les calculs IR.',
    valueType: 'scale',
    unit: 'percent',
    millesime: '2026',
    effectiveFrom: '2026-01-01',
    source: completeSource(
      ['boi-ir-liq-20-10', 'cgi-197', 'cgi-193-197'],
      ['income-tax-scale-current'],
      'Le chaînage Settings référence le BOFiP et les articles CGI qui fondent le barème IR.',
    ),
    defaultValue: settingsDefault('tax_settings', 'incomeTax.scaleCurrent'),
    currentValue: currentJsonb('tax_settings', 'incomeTax.scaleCurrent'),
    validation: scaleValidation,
    ownerSettingsPage: ownerMemento,
    consumerSimulatorIds: [
      'ir',
      'per',
      'per-potentiel',
      'investissement-locatif',
      'revenus-fonciers',
      'lmnp-lmp',
      'remuneration',
    ],
    status: 'ready',
    statusReason: 'Barème éditable dans Impôts, chaîné à settings-references et normalisé.',
  },
  {
    family: 'impots',
    key: 'impots.ir.abattements-et-decote',
    label: 'Décote, quotient familial et abattements IR',
    description: 'Plafonds et abattements IR courants nécessaires aux simulateurs IR/PER.',
    valueType: 'object',
    unit: 'eur',
    millesime: '2026',
    effectiveFrom: '2026-01-01',
    source: completeSource(
      ['boi-ir-liq-20-20-30', 'boi-ir-liq-20-20-20', 'boi-rsa-pens-30-10-10', 'cgi-197'],
      [
        'income-tax-decote-current',
        'quotient-familial-plafond-current',
        'abat10-pensions-current',
        'abat10-salaries-current',
        'income-tax-dom-abatement-current',
      ],
      'Les claims Settings couvrent la décote, le quotient familial et les abattements IR.',
    ),
    defaultValue: settingsDefault('tax_settings', 'incomeTax'),
    currentValue: currentJsonb('tax_settings', 'incomeTax'),
    validation: {
      validators: ['validatePositive', 'validatePercent'],
      rules: ['Montants positifs et taux en pourcentage utilisateur.'],
      requiredBeforeConsumption: true,
    },
    ownerSettingsPage: ownerMemento,
    consumerSimulatorIds: ['ir', 'per', 'per-potentiel'],
    status: 'ready',
    statusReason: 'Les sous-claims IR sont déclarés et validés par la section fiscale du mémento.',
  },
  {
    family: 'impots',
    key: 'impots.pfu.part-ir',
    label: 'PFU - part IR',
    description: 'Part impôt sur le revenu du PFU, la part sociale venant des prélèvements.',
    valueType: 'percent',
    unit: 'percent',
    millesime: '2026',
    effectiveFrom: '2026-01-01',
    source: completeSource(
      ['boi-rppm-rcm-30-20', 'cgi-200-a'],
      ['pfu-ir-current'],
      'Le claim PFU rattache la part IR du prélèvement forfaitaire aux sources BOFiP/CGI.',
    ),
    defaultValue: settingsDefault('tax_settings', 'pfu.current.rateIR'),
    currentValue: currentJsonb('tax_settings', 'pfu.current.rateIR'),
    validation: percentValidation,
    ownerSettingsPage: ownerMemento,
    consumerSimulatorIds: ['ir', 'placement', 'per-potentiel', 'cession-titres', 'sortie-capitaux'],
    status: 'ready',
    statusReason: 'Valeur éditable et consommée via useFiscalContext.pfuRateIR.',
  },
  {
    family: 'impots',
    key: 'impots.cehr',
    label: 'CEHR',
    description: 'Tranches de contribution exceptionnelle sur les hauts revenus.',
    valueType: 'scale',
    unit: 'percent',
    millesime: '2026',
    effectiveFrom: '2026-01-01',
    source: completeSource(
      ['boi-ir-chr', 'cgi-223-sexies'],
      ['cehr-current'],
      'Le claim CEHR rattache les tranches courantes au BOFiP et à l’article 223 sexies CGI.',
    ),
    defaultValue: settingsDefault('tax_settings', 'cehr.current'),
    currentValue: currentJsonb('tax_settings', 'cehr.current'),
    validation: scaleValidation,
    ownerSettingsPage: ownerMemento,
    consumerSimulatorIds: ['ir'],
    status: 'ready',
    statusReason: 'Valeur éditable dans le mémento et couverte par settings-references.',
  },
  {
    family: 'impots',
    key: 'impots.cdhr',
    label: 'CDHR',
    description: 'Contribution différentielle hauts revenus : seuils et taux effectif minimal.',
    valueType: 'object',
    unit: 'percent',
    millesime: '2026',
    effectiveFrom: '2026-01-01',
    source: completeSource(
      ['cgi-224'],
      ['cdhr-current'],
      'Le claim CDHR rattache les seuils et le taux minimal à l’article CGI dédié.',
    ),
    defaultValue: settingsDefault('tax_settings', 'cdhr.current'),
    currentValue: currentJsonb('tax_settings', 'cdhr.current'),
    validation: {
      validators: ['validatePercent', 'validatePositive'],
      rules: ['Taux en pourcentage et seuils positifs.'],
      requiredBeforeConsumption: true,
    },
    ownerSettingsPage: ownerMemento,
    consumerSimulatorIds: ['ir'],
    status: 'ready',
    statusReason: 'Normalisé dans useFiscalContext.cdhr et affiché dans le mémento.',
  },
  {
    family: 'impots',
    key: 'impots.ifi.bareme',
    label: 'IFI - seuil et barème courant',
    description: 'Seuil d’entrée, abattement résidence principale et barème IFI courant.',
    valueType: 'scale',
    unit: 'percent',
    millesime: '2026',
    effectiveFrom: '2026-01-01',
    source: completeSource(
      ['boi-pat-ifi-40-10', 'cgi-964', 'cgi-977'],
      ['ifi-current'],
      'Le claim IFI rattache le barème courant aux sources BOFiP et CGI.',
    ),
    defaultValue: settingsDefault('tax_settings', 'ifi.current'),
    currentValue: currentJsonb('tax_settings', 'ifi.current'),
    validation: scaleValidation,
    ownerSettingsPage: ownerMemento,
    consumerSimulatorIds: ['ifi', 'succession', 'donation-demembrement'],
    status: 'ready',
    statusReason:
      'Barème présent dans defaults, éditable dans le mémento et normalisé dans useFiscalContext.',
  },
  {
    family: 'impots',
    key: 'impots.ifi.millesimes',
    label: 'IFI - millésimes historiques',
    description: 'Historique des barèmes IFI pour projections ou dossiers antérieurs.',
    valueType: 'object',
    unit: 'year',
    millesime: 'a-renseigner-avant-codage',
    source: sourceToComplete(
      'BOFiP/CGI IFI par année à qualifier avant codage.',
      'Le barème courant est prêt ; les millésimes historiques restent planifiés.',
      ['boi-pat-ifi-40-10', 'cgi-964', 'cgi-977'],
    ),
    defaultValue: null,
    currentValue: null,
    validation: plannedValidation,
    ownerSettingsPage: ownerMemento,
    consumerSimulatorIds: ['ifi'],
    status: 'planned',
    statusReason:
      'Inventaire attendu pour les futures projections, sans valeur inventée dans F0.5.',
  },
  {
    family: 'comptables-societes',
    key: 'comptables-societes.is',
    label: 'Impôt sur les sociétés',
    description: 'Taux normal, taux réduit, seuil réduit et paramètres IS courants.',
    valueType: 'object',
    unit: 'percent',
    millesime: '2026',
    effectiveFrom: '2026-01-01',
    source: completeSource(
      ['cgi-209', 'cgi-219', 'boi-is-liq-10', 'boi-is-liq-20'],
      ['corporate-tax-current'],
      'Le claim corporate-tax-current couvre l’IS et ses paramètres associés.',
    ),
    defaultValue: settingsDefault('tax_settings', 'corporateTax.current'),
    currentValue: currentJsonb('tax_settings', 'corporateTax.current'),
    validation: {
      validators: ['validateCorporateTaxSettings', 'validateQpfcRate'],
      rules: ['Taux entre 0 et 100, seuils positifs, QPFC standard supérieure au groupe.'],
      requiredBeforeConsumption: true,
    },
    ownerSettingsPage: ownerMemento,
    consumerSimulatorIds: ['tresorerie-societe', 'projection-comptable'],
    status: 'ready',
    statusReason:
      'Section Comptables & sociétés du mémento active, sauvegarde tax_settings et référence chaînée.',
  },
  {
    family: 'comptables-societes',
    key: 'comptables-societes.mere-fille-qpfc',
    label: 'Régime mère-fille - QPFC',
    description: 'Quote-part de frais et charges standard/groupe, incluse dans corporateTax.',
    valueType: 'object',
    unit: 'percent',
    millesime: '2026',
    effectiveFrom: '2026-01-01',
    source: completeSource(
      ['cgi-209', 'cgi-219', 'boi-is-liq-10'],
      ['corporate-tax-current'],
      'La QPFC mère-fille est couverte par le claim corporate-tax-current.',
    ),
    defaultValue: settingsDefault('tax_settings', 'corporateTax.current.motherDaughterQpfc'),
    currentValue: currentJsonb('tax_settings', 'corporateTax.current.motherDaughterQpfc'),
    validation: {
      validators: ['validateQpfcRate'],
      rules: ['QPFC standard supérieure ou égale au régime groupe.'],
      requiredBeforeConsumption: true,
    },
    ownerSettingsPage: ownerMemento,
    consumerSimulatorIds: ['tresorerie-societe', 'holding'],
    status: 'partial',
    statusReason:
      'Le taux est prêt ; les conditions holding/mère-fille détaillées restent à spécifier.',
  },
  {
    family: 'impots',
    key: 'impots.ps-patrimoine',
    label: 'Prélèvements sociaux patrimoine',
    description: 'Taux patrimoine courant, exception et CSG déductible.',
    valueType: 'object',
    unit: 'percent',
    millesime: '2026',
    effectiveFrom: '2026-01-01',
    source: completeSource(
      ['service-public-ps-revenus-capital-2026', 'css-l136-6', 'css-l136-8', 'css-l136-7'],
      ['patrimony-current'],
      'Le claim patrimoine rattache les taux PS aux sources Service-Public et Code de la sécurité sociale.',
    ),
    defaultValue: settingsDefault('ps_settings', 'patrimony.current'),
    currentValue: currentJsonb('ps_settings', 'patrimony.current'),
    validation: percentValidation,
    ownerSettingsPage: ownerMemento,
    consumerSimulatorIds: [
      'ir',
      'placement',
      'per-potentiel',
      'per-transfert',
      'investissement-locatif',
      'revenus-fonciers',
      'plus-values-immobilieres',
      'arbitrage-reemploi',
      'cession-titres',
      'sortie-capitaux',
    ],
    status: 'ready',
    statusReason: 'Paramètre éditable dans le mémento et consommé via useFiscalContext.',
  },
  {
    family: 'retraite-prevoyance',
    key: 'retraite-prevoyance.ps-retraite',
    label: 'Prélèvements sociaux retraite',
    description: 'Barèmes PS retraite courants par tranche.',
    valueType: 'scale',
    unit: 'percent',
    millesime: '2026',
    effectiveFrom: '2026-01-01',
    source: completeSource(
      ['css-l136-8'],
      ['retirement-current-brackets'],
      'Le claim retraite courant couvre les tranches PS retraite exposées en Settings.',
    ),
    defaultValue: settingsDefault('ps_settings', 'retirement.current.brackets'),
    currentValue: currentJsonb('ps_settings', 'retirement.current.brackets'),
    validation: scaleValidation,
    ownerSettingsPage: ownerMemento,
    consumerSimulatorIds: ['retraite', 'per-transfert'],
    status: 'ready',
    statusReason: 'Barème éditable dans le mémento et normalisé dans useFiscalContext.',
  },
  {
    family: 'retraite-prevoyance',
    key: 'retraite-prevoyance.seuils-rfr',
    label: 'Seuils RFR retraite',
    description: 'Seuils de RFR par résidence pour déterminer les taux sociaux retraite.',
    valueType: 'threshold',
    unit: 'eur',
    millesime: '2026',
    effectiveFrom: '2026-01-01',
    source: completeSource(
      ['css-l136-8'],
      ['retirement-thresholds-current'],
      'Le claim seuils RFR retraite rattache les seuils au Code de la sécurité sociale.',
    ),
    defaultValue: settingsDefault('ps_settings', 'retirementThresholds.current'),
    currentValue: currentJsonb('ps_settings', 'retirementThresholds.current'),
    validation: {
      validators: ['validatePositive'],
      rules: ['Seuils positifs et millésime cohérent avec les labels IR/RFR.'],
      requiredBeforeConsumption: true,
    },
    ownerSettingsPage: ownerMemento,
    consumerSimulatorIds: ['retraite'],
    status: 'ready',
    statusReason: 'Seuils éditables et chaînés à settings-references.',
  },
  {
    family: 'retraite-prevoyance',
    key: 'retraite-prevoyance.pass',
    label: 'PASS',
    description: 'Historique du plafond annuel de la sécurité sociale.',
    valueType: 'amount',
    unit: 'eur',
    millesime: '2026',
    effectiveFrom: '2026-01-01',
    source: completeSource(
      ['urssaf-pass-2026', 'ameli-pass-2026'],
      ['pass-latest'],
      'Le PASS est administré via pass_history et recoupé par les sources URSSAF/Ameli.',
    ),
    defaultValue: { kind: 'pass-history', year: 'latest' },
    currentValue: { kind: 'supabase-table', table: 'pass_history', path: 'year/pass_amount' },
    validation: {
      validators: ['check:settings-references', 'usePassHistory'],
      rules: ['Millésime annuel présent dans DEFAULT_PASS_HISTORY et pass_history.'],
      requiredBeforeConsumption: true,
    },
    ownerSettingsPage: ownerMemento,
    consumerSimulatorIds: ['per', 'per-potentiel', 'per-transfert', 'retraite'],
    status: 'ready',
    statusReason: 'Table pass_history chargée par fiscalSettingsCache avec fallback documenté.',
  },
  {
    family: 'transmission',
    key: 'transmission.dmtg-succession',
    label: 'DMTG succession',
    description: 'Barèmes et abattements des droits de mutation à titre gratuit.',
    valueType: 'scale',
    unit: 'percent',
    millesime: '2026',
    effectiveFrom: '2026-01-01',
    source: completeSource(
      ['boi-enr-dmtg-10-50-30', 'boi-enr-dmtg-10-50-20', 'cgi-777', 'cgi-779'],
      [
        'donation-rapport-reduction',
        'dmtg-fiscal-values-current',
        'dmtg-conjoint-pacs-exoneration-cgi-796-0-bis',
        'don-familial-sommes-790g',
        'donation-rappel-fiscal-15-ans',
        'usufruit-nue-propriete-cgi-669',
      ],
      'Les claims DMTG courants rattachent tarifs, abattements, donations et usufruit aux sources BOFiP/CGI.',
    ),
    defaultValue: settingsDefault('tax_settings', 'dmtg'),
    currentValue: currentJsonb('tax_settings', 'dmtg'),
    validation: {
      validators: ['validateDmtg', 'checkDmtgGoldenScenario'],
      rules: ['Barèmes ordonnés, abattements positifs, golden scenario DMTG conservé.'],
      requiredBeforeConsumption: true,
    },
    ownerSettingsPage: ownerMemento,
    consumerSimulatorIds: [
      'donations-anterieures',
      'placement',
      'sci',
      'succession',
      'donation-demembrement',
      'pacte-dutreil',
    ],
    status: 'ready',
    statusReason: 'Édité dans le mémento et consommé par le contexte fiscal strict.',
  },
  {
    family: 'transmission',
    key: 'transmission.assurance-vie-deces',
    label: 'Assurance-vie décès',
    description: 'Règles 990 I / 757 B applicables au décès.',
    valueType: 'ruleset',
    unit: 'eur',
    millesime: '2026',
    effectiveFrom: '2026-01-01',
    source: completeSource(
      ['boi-tcas-aut-60', 'cgi-990-i', 'boi-enr-dmtg-10-10-20-20', 'cgi-757-b'],
      ['assurance-vie-990i-757b'],
      'Le claim assurance-vie décès couvre les régimes 990 I et 757 B.',
    ),
    defaultValue: settingsDefault('fiscality_settings', 'rulesetsByKey.assuranceVie.rules.deces'),
    currentValue: currentJsonb('fiscality_settings', 'rulesetsByKey.assuranceVie.rules.deces'),
    validation: {
      validators: ['validateAvDeces'],
      rules: ['Âge pivot borné, abattements positifs et taux en pourcentage.'],
      requiredBeforeConsumption: true,
    },
    ownerSettingsPage: ownerMemento,
    consumerSimulatorIds: ['succession', 'placement'],
    status: 'ready',
    statusReason: 'Règles décès éditables dans le mémento et chaînées.',
  },
  {
    family: 'placements',
    key: 'placements.assurance-vie-capitalisation',
    label: 'Assurance-vie / capitalisation',
    description: 'Règles d’enveloppe assurance-vie et capitalisation pour placement/transmission.',
    valueType: 'ruleset',
    unit: 'none',
    millesime: '2026',
    source: sourceToComplete(
      'Sources sortie/rachat et capitalisation à compléter avant pack placement exhaustif.',
      'Le décès assurance-vie est prêt ; le pack enveloppe complet reste partiel.',
      ['boi-tcas-aut-60', 'cgi-990-i', 'cgi-757-b'],
    ),
    defaultValue: settingsDefault('fiscality_settings', 'rulesetsByKey.assuranceVie.rules'),
    currentValue: currentJsonb('fiscality_settings', 'rulesetsByKey.assuranceVie.rules'),
    validation: {
      validators: ['validateAvDeces', 'check:settings-registry'],
      rules: ['Les sous-règles non sourcées restent interdites en consommation future.'],
      requiredBeforeConsumption: true,
    },
    ownerSettingsPage: ownerMemento,
    consumerSimulatorIds: ['placement', 'succession', 'scpi', 'arbitrage-reemploi'],
    status: 'partial',
    statusReason: 'Des règles existent, mais le pack placement complet n’est pas attesté.',
  },
  {
    family: 'placements',
    key: 'placements.per-individuel',
    label: 'PER individuel',
    description: 'Règles PER individuelles présentes en defaults mais à chaîner plus finement.',
    valueType: 'ruleset',
    unit: 'none',
    millesime: '2026',
    source: sourceToComplete(
      'Références Settings PER à détailler dans settings-references avant extension moteur.',
      'Les simulateurs PER consomment déjà des règles centralisées, mais le chaînage claim par claim reste partiel.',
      ['cgi-154-bis', 'cgi-163-quatervicies', 'cmf-l224-1'],
    ),
    defaultValue: settingsDefault('fiscality_settings', 'rulesetsByKey.perIndividuel.rules'),
    currentValue: currentJsonb('fiscality_settings', 'rulesetsByKey.perIndividuel.rules'),
    validation: {
      validators: ['check:settings-registry'],
      rules: ['Chaque sous-règle PER future doit recevoir un claim settings-references dédié.'],
      requiredBeforeConsumption: true,
    },
    ownerSettingsPage: ownerMemento,
    consumerSimulatorIds: ['per', 'per-potentiel', 'per-transfert'],
    status: 'partial',
    statusReason: 'Centralisé dans fiscality_settings mais non exhaustivement chaîné.',
  },
] as const satisfies readonly SettingsRegistryEntry[];
