import type { SettingsRegistryEntry } from './types';
import {
  ownerDmtg,
  ownerMemento,
  ownerPrelevements,
  plannedValidation,
  sourceToComplete,
} from './entryHelpers';

export const SETTINGS_PLANNED_REGISTRY = [
  {
    family: 'immobilier',
    key: 'immobilier.pv-immobilieres.abattements-duree',
    label: 'Plus-values immobilières - abattements durée',
    description: 'Abattements IR/PS par durée de détention pour les cessions immobilières.',
    valueType: 'scale',
    unit: 'percent',
    millesime: 'a-renseigner-avant-codage',
    source: sourceToComplete(
      'BOFiP plus-values immobilières et textes CGI à rattacher avant moteur.',
      'Paramètre nécessaire au futur simulateur plus-values immobilières, sans valeur dans F0.5.',
    ),
    defaultValue: null,
    currentValue: null,
    validation: plannedValidation,
    ownerSettingsPage: ownerMemento,
    consumerSimulatorIds: ['plus-values-immobilieres', 'arbitrage-reemploi'],
    status: 'planned',
    statusReason: 'Reporté au pack moteur immobilier pour éviter toute valeur non sourcée.',
  },
  {
    family: 'immobilier',
    key: 'immobilier.revenus-fonciers.micro-foncier',
    label: 'Revenus fonciers - micro-foncier',
    description: 'Seuil et abattement du régime micro-foncier.',
    valueType: 'object',
    unit: 'eur',
    millesime: 'a-renseigner-avant-codage',
    source: sourceToComplete(
      'BOFiP revenus fonciers et CGI micro-foncier à qualifier avant codage.',
      'Le futur moteur revenus fonciers doit déclarer ce pack avant consommation.',
    ),
    defaultValue: null,
    currentValue: null,
    validation: plannedValidation,
    ownerSettingsPage: ownerMemento,
    consumerSimulatorIds: ['revenus-fonciers', 'investissement-locatif', 'scpi'],
    status: 'planned',
    statusReason: 'Inventaire seulement ; aucun seuil ni abattement ajouté.',
  },
  {
    family: 'immobilier',
    key: 'immobilier.lmnp-lmp.regimes',
    label: 'LMNP / LMP - régimes',
    description: 'Seuils et abattements des régimes meublés, amortissements à cadrer.',
    valueType: 'object',
    unit: 'eur',
    millesime: 'a-renseigner-avant-codage',
    source: sourceToComplete(
      'BOFiP BIC/location meublée et textes LMP/LMNP à rattacher avant moteur.',
      'Le futur moteur LMNP/LMP doit compléter ces références avant de calculer.',
    ),
    defaultValue: null,
    currentValue: null,
    validation: plannedValidation,
    ownerSettingsPage: ownerMemento,
    consumerSimulatorIds: ['lmnp-lmp', 'investissement-locatif'],
    status: 'planned',
    statusReason: 'Régime métier à cadrer avec le futur moteur, sans valeur inventée.',
  },
  {
    family: 'immobilier',
    key: 'immobilier.scpi.regime',
    label: 'SCPI - régime revenus et cession',
    description:
      'Paramètres fiscaux attendus pour SCPI détenues en direct, à crédit ou via enveloppe.',
    valueType: 'ruleset',
    unit: 'none',
    millesime: 'a-renseigner-avant-codage',
    source: sourceToComplete(
      'Sources revenus fonciers, plus-values et fiscalité enveloppe SCPI à qualifier.',
      'SCPI reste un sous-parcours futur ; le registry bloque toute consommation non déclarée.',
    ),
    defaultValue: null,
    currentValue: null,
    validation: plannedValidation,
    ownerSettingsPage: ownerMemento,
    consumerSimulatorIds: ['scpi'],
    status: 'planned',
    statusReason: 'Le simulateur SCPI n’est pas ouvert ; le pack fiscal reste planned.',
  },
  {
    family: 'comptables-societes',
    key: 'comptables-societes.pv-mobilieres',
    label: 'Plus-values mobilières / cession de titres',
    description: 'Régimes de cession de titres, report, réemploi et abattements éventuels.',
    valueType: 'ruleset',
    unit: 'none',
    millesime: 'a-renseigner-avant-codage',
    source: sourceToComplete(
      'BOFiP plus-values mobilières, CGI 150-0 A et régimes dirigeants à compléter.',
      'Le futur moteur cession de titres doit compléter ce pack avant consommation.',
    ),
    defaultValue: null,
    currentValue: null,
    validation: plannedValidation,
    ownerSettingsPage: ownerMemento,
    consumerSimulatorIds: ['cession-titres', 'holding', 'arbitrage-reemploi'],
    status: 'planned',
    statusReason: 'Planifié pour Société & dirigeant, sans valeur de cession codée.',
  },
  {
    family: 'comptables-societes',
    key: 'comptables-societes.dividendes',
    label: 'Dividendes',
    description: 'Paramètres de distribution et fiscalité dividendes côté société/dirigeant.',
    valueType: 'ruleset',
    unit: 'percent',
    millesime: 'a-renseigner-avant-codage',
    source: sourceToComplete(
      'Sources dividendes, PFU/barème et assiette sociale dirigeant à qualifier.',
      'Le taux d’abattement présent dans corporateTax n’épuise pas le futur pack dividendes.',
    ),
    defaultValue: null,
    currentValue: null,
    validation: plannedValidation,
    ownerSettingsPage: ownerMemento,
    consumerSimulatorIds: ['remuneration', 'sortie-capitaux'],
    status: 'planned',
    statusReason: 'Nécessite le modèle dirigeant/société, reporté hors F0.5.',
  },
  {
    family: 'comptables-societes',
    key: 'comptables-societes.holding-apport-cession',
    label: 'Holding / apport-cession',
    description: 'Règles de structuration holding, apport-cession et réemploi.',
    valueType: 'ruleset',
    unit: 'none',
    millesime: 'a-renseigner-avant-codage',
    source: sourceToComplete(
      'Régimes holding, apport-cession et réemploi à sourcer avant moteur.',
      'La QPFC mère-fille prête ne suffit pas au futur parcours holding.',
    ),
    defaultValue: null,
    currentValue: null,
    validation: plannedValidation,
    ownerSettingsPage: ownerMemento,
    consumerSimulatorIds: ['holding', 'cession-titres'],
    status: 'planned',
    statusReason: 'Planifié pour PR Société & dirigeant, sans moteur ni valeurs.',
  },
  {
    family: 'transmission',
    key: 'transmission.dutreil',
    label: 'Pacte Dutreil',
    description: 'Exonération, durées d’engagement et conditions du pacte Dutreil.',
    valueType: 'ruleset',
    unit: 'percent',
    millesime: 'a-renseigner-avant-codage',
    source: sourceToComplete(
      'CGI/BOFiP Dutreil à compléter avant simulateur transmission entreprise.',
      'Le futur moteur Dutreil doit compléter les références et validations.',
    ),
    defaultValue: null,
    currentValue: null,
    validation: plannedValidation,
    ownerSettingsPage: ownerDmtg,
    consumerSimulatorIds: ['pacte-dutreil', 'donation-demembrement'],
    status: 'planned',
    statusReason: 'Inventaire nécessaire, sans exonération ni durée inventée.',
  },
  {
    family: 'retraite-prevoyance',
    key: 'retraite-prevoyance.cotisations-retraite',
    label: 'Cotisations retraite',
    description: 'Barèmes de constitution des droits retraite et cotisations associées.',
    valueType: 'scale',
    unit: 'eur',
    millesime: 'a-renseigner-avant-codage',
    source: sourceToComplete(
      'BOSS/caisses retraite et textes sécurité sociale à rattacher par régime.',
      'Le futur moteur retraite globale doit compléter ce pack avant calcul.',
    ),
    defaultValue: null,
    currentValue: null,
    validation: plannedValidation,
    ownerSettingsPage: ownerPrelevements,
    consumerSimulatorIds: ['retraite', 'remuneration'],
    status: 'planned',
    statusReason: 'Dépend des futurs régimes retraite et du dossier dirigeant.',
  },
  {
    family: 'retraite-prevoyance',
    key: 'retraite-prevoyance.validation-retraite-600-smic',
    label: 'Validation retraite - seuil 600 SMIC',
    description: 'Seuil annuel de revenus/cotisations pour validation retraite à qualifier.',
    valueType: 'threshold',
    unit: 'eur',
    millesime: 'a-renseigner-avant-codage',
    source: sourceToComplete(
      'Source officielle retraite/SMIC à identifier avant toute règle de validation.',
      'Le seuil est demandé comme inventaire planned ; aucune valeur n’est ajoutée.',
    ),
    defaultValue: null,
    currentValue: null,
    validation: plannedValidation,
    ownerSettingsPage: ownerPrelevements,
    consumerSimulatorIds: ['retraite', 'remuneration'],
    status: 'planned',
    statusReason: 'Bloqué tant que le modèle retraite globale n’existe pas.',
  },
  {
    family: 'retraite-prevoyance',
    key: 'retraite-prevoyance.prevoyance-garanties',
    label: 'Prévoyance - garanties et cotisations',
    description: 'Paramètres de garanties, cotisations et sources prévoyance par régime.',
    valueType: 'ruleset',
    unit: 'none',
    millesime: 'a-renseigner-avant-codage',
    source: sourceToComplete(
      'Sources prévoyance en base à compléter et auditer avec --with-db par catégorie.',
      'La page Prévoyance régimes existe ; ce pack transverse reste partiel pour les futurs moteurs.',
    ),
    defaultValue: null,
    currentValue: null,
    validation: plannedValidation,
    ownerSettingsPage: '/settings/prevoyance-regimes',
    consumerSimulatorIds: ['retraite'],
    status: 'planned',
    statusReason: 'Inventaire transverse uniquement, sans duplication des sources Supabase.',
  },
  {
    family: 'social-dirigeant',
    key: 'social-dirigeant.puma-csm',
    label: 'PUMA / CSM',
    description: 'Contribution subsidiaire maladie et paramètres PUMA à qualifier.',
    valueType: 'ruleset',
    unit: 'percent',
    millesime: 'a-renseigner-avant-codage',
    source: sourceToComplete(
      'Sources CSS/URSSAF PUMA-CSM à identifier avant codage.',
      'Le registry déclare le besoin sans valeur ni calcul.',
    ),
    defaultValue: null,
    currentValue: null,
    validation: plannedValidation,
    ownerSettingsPage: ownerPrelevements,
    consumerSimulatorIds: ['remuneration', 'retraite', 'sortie-capitaux'],
    status: 'planned',
    statusReason: 'Reporté aux PR social dirigeant/retraite globale.',
  },
  {
    family: 'placements',
    key: 'placements.epargne-salariale',
    label: 'Épargne salariale',
    description: 'Paramètres d’intéressement, participation, abondement, PEE/PERCOL.',
    valueType: 'ruleset',
    unit: 'eur',
    millesime: 'a-renseigner-avant-codage',
    source: sourceToComplete(
      'Code du travail, BOSS/URSSAF et plafonds dispositifs à rattacher avant moteur.',
      'La route est placeholder ; les paramètres restent planned et non éditables.',
      ['code-travail-l3312-1', 'code-travail-l3332-1'],
    ),
    defaultValue: null,
    currentValue: null,
    validation: plannedValidation,
    ownerSettingsPage: ownerPrelevements,
    consumerSimulatorIds: ['remuneration'],
    status: 'planned',
    statusReason: 'Déclaré pour bloquer toute consommation avant pack dédié.',
  },
] as const satisfies readonly SettingsRegistryEntry[];
