/**
 * domain/base-contrat/catalog.ts
 *
 * Catalogue hardcodé des produits patrimoniaux.
 * Source de vérité PR1 — 100% additive, aucun impact runtime.
 *
 * Champs retenus (minimum nécessaire) :
 *   id, label, grandeFamille, catalogKind, ppEligible, pmEligible, templateKey
 *
 * isActive = true par défaut ; closedDate géré via base_contrat_overrides (PR1.6).
 * Pas de commentaires de qualification ni de références longues (PR1 légère).
 */

import type { CatalogKind, GrandeFamille } from './types';

export interface CatalogProduct {
  id: string;
  label: string;
  grandeFamille: GrandeFamille;
  catalogKind: CatalogKind;
  ppEligible: boolean;
  pmEligible: boolean;
  templateKey: string | null;
}

export const CATALOG: CatalogProduct[] = [
  // ── Assurance prévoyance ─────────────────────────────────────────────────
  {
    id: 'assurance_dependance',
    label: 'Assurance dépendance',
    grandeFamille: 'Assurance prévoyance',
    catalogKind: 'protection',
    ppEligible: true,
    pmEligible: false,
    templateKey: null,
  },
  {
    id: 'assurance_emprunteur',
    label: 'Assurance emprunteur',
    grandeFamille: 'Assurance prévoyance',
    catalogKind: 'protection',
    ppEligible: true,
    pmEligible: true,
    templateKey: null,
  },
  {
    id: 'assurance_obseques',
    label: 'Assurance obsèques',
    grandeFamille: 'Assurance prévoyance',
    catalogKind: 'protection',
    ppEligible: true,
    pmEligible: false,
    templateKey: null,
  },
  {
    id: 'prevoyance_individuelle_deces',
    label: 'Prévoyance individuelle décès',
    grandeFamille: 'Assurance prévoyance',
    catalogKind: 'protection',
    ppEligible: true,
    pmEligible: false,
    templateKey: 'insurance_risk_generic',
  },
  {
    id: 'prevoyance_individuelle_itt_invalidite',
    label: 'Prévoyance individuelle arrêt de travail / invalidité',
    grandeFamille: 'Assurance prévoyance',
    catalogKind: 'protection',
    ppEligible: true,
    pmEligible: false,
    templateKey: 'insurance_risk_generic',
  },
  {
    id: 'assurance_homme_cle',
    label: 'Assurance homme-clé',
    grandeFamille: 'Assurance prévoyance',
    catalogKind: 'protection',
    ppEligible: false,
    pmEligible: true,
    templateKey: 'insurance_risk_generic',
  },

  // ── Épargne Assurance ────────────────────────────────────────────────────
  {
    id: 'assurance_vie',
    label: 'Assurance-vie',
    grandeFamille: 'Épargne Assurance',
    catalogKind: 'wrapper',
    ppEligible: true,
    pmEligible: false,
    templateKey: 'insurance_life_savings',
  },
  {
    id: 'contrat_capitalisation',
    label: 'Contrat de capitalisation',
    grandeFamille: 'Épargne Assurance',
    catalogKind: 'wrapper',
    ppEligible: true,
    pmEligible: true,
    templateKey: 'capitalisation_contract',
  },

  // ── Épargne bancaire ─────────────────────────────────────────────────────
  {
    id: 'cat_compte_a_terme',
    label: 'Compte à terme / dépôt à terme (CAT)',
    grandeFamille: 'Épargne bancaire',
    catalogKind: 'wrapper',
    ppEligible: true,
    pmEligible: true,
    templateKey: 'bank_account',
  },
  {
    id: 'compte_courant_depot',
    label: 'Compte courant (compte de dépôt)',
    grandeFamille: 'Épargne bancaire',
    catalogKind: 'wrapper',
    ppEligible: true,
    pmEligible: true,
    templateKey: 'bank_account',
  },
  {
    id: 'csl_compte_sur_livret',
    label: 'Compte sur livret (CSL)',
    grandeFamille: 'Épargne bancaire',
    catalogKind: 'wrapper',
    ppEligible: true,
    pmEligible: true,
    templateKey: 'bank_account',
  },
  {
    id: 'cel',
    label: 'CEL (Compte épargne logement)',
    grandeFamille: 'Épargne bancaire',
    catalogKind: 'wrapper',
    ppEligible: true,
    pmEligible: false,
    templateKey: 'bank_account',
  },
  {
    id: 'ldds',
    label: 'LDDS',
    grandeFamille: 'Épargne bancaire',
    catalogKind: 'wrapper',
    ppEligible: true,
    pmEligible: false,
    templateKey: 'regulated_savings',
  },
  {
    id: 'lep',
    label: 'LEP',
    grandeFamille: 'Épargne bancaire',
    catalogKind: 'wrapper',
    ppEligible: true,
    pmEligible: false,
    templateKey: 'regulated_savings',
  },
  {
    id: 'livret_a',
    label: 'Livret A',
    grandeFamille: 'Épargne bancaire',
    catalogKind: 'wrapper',
    ppEligible: true,
    pmEligible: false,
    templateKey: 'regulated_savings',
  },
  {
    id: 'livret_jeune',
    label: 'Livret Jeune',
    grandeFamille: 'Épargne bancaire',
    catalogKind: 'wrapper',
    ppEligible: true,
    pmEligible: false,
    templateKey: 'regulated_savings',
  },
  {
    id: 'pel',
    label: 'PEL (Plan épargne logement)',
    grandeFamille: 'Épargne bancaire',
    catalogKind: 'wrapper',
    ppEligible: true,
    pmEligible: false,
    templateKey: 'bank_account',
  },
  {
    id: 'peac',
    label: 'PEAC (Plan d\'épargne avenir climat)',
    grandeFamille: 'Épargne bancaire',
    catalogKind: 'wrapper',
    ppEligible: true,
    pmEligible: false,
    templateKey: 'regulated_savings',
  },
  {
    id: 'cto',
    label: 'Compte-titres ordinaire (CTO)',
    grandeFamille: 'Épargne bancaire',
    catalogKind: 'wrapper',
    ppEligible: true,
    pmEligible: true,
    templateKey: 'securities_account',
  },
  {
    id: 'pea',
    label: 'PEA (Plan d\'épargne en actions)',
    grandeFamille: 'Épargne bancaire',
    catalogKind: 'wrapper',
    ppEligible: true,
    pmEligible: false,
    templateKey: 'securities_account',
  },
  {
    id: 'pea_pme',
    label: 'PEA-PME',
    grandeFamille: 'Épargne bancaire',
    catalogKind: 'wrapper',
    ppEligible: true,
    pmEligible: false,
    templateKey: 'securities_account',
  },

  // ── Retraite & épargne salariale ─────────────────────────────────────────
  {
    id: 'article_83',
    label: 'Article 83 (anciens contrats "retraite entreprise")',
    grandeFamille: 'Retraite & épargne salariale',
    catalogKind: 'wrapper',
    ppEligible: true,
    pmEligible: true,
    templateKey: 'retirement_company',
  },
  {
    id: 'article_39',
    label: 'Article 39 (retraite supplémentaire à prestations définies)',
    grandeFamille: 'Retraite & épargne salariale',
    catalogKind: 'wrapper',
    ppEligible: true,
    pmEligible: true,
    templateKey: 'retirement_company',
  },
  {
    id: 'madelin_retraite_ancien',
    label: 'Madelin retraite (ancien)',
    grandeFamille: 'Retraite & épargne salariale',
    catalogKind: 'wrapper',
    ppEligible: true,
    pmEligible: false,
    templateKey: 'retirement_individual',
  },
  {
    id: 'pee',
    label: 'PEE (Plan d\'épargne entreprise)',
    grandeFamille: 'Retraite & épargne salariale',
    catalogKind: 'wrapper',
    ppEligible: true,
    pmEligible: true,
    templateKey: 'employee_savings_plan',
  },
  {
    id: 'perin_assurance',
    label: 'PERIN assurantiel (PER individuel assurance)',
    grandeFamille: 'Retraite & épargne salariale',
    catalogKind: 'wrapper',
    ppEligible: true,
    pmEligible: false,
    templateKey: 'retirement_individual',
  },
  {
    id: 'perin_bancaire',
    label: 'PERIN bancaire (PER individuel compte-titres)',
    grandeFamille: 'Retraite & épargne salariale',
    catalogKind: 'wrapper',
    ppEligible: true,
    pmEligible: false,
    templateKey: 'retirement_individual',
  },
  {
    id: 'percol',
    label: 'PERCOL (PER collectif)',
    grandeFamille: 'Retraite & épargne salariale',
    catalogKind: 'wrapper',
    ppEligible: true,
    pmEligible: true,
    templateKey: 'retirement_company',
  },
  {
    id: 'perco_ancien',
    label: 'PERCO (ancien)',
    grandeFamille: 'Retraite & épargne salariale',
    catalogKind: 'wrapper',
    ppEligible: true,
    pmEligible: true,
    templateKey: 'retirement_company',
  },
  {
    id: 'pero',
    label: 'PERO (PER obligatoire)',
    grandeFamille: 'Retraite & épargne salariale',
    catalogKind: 'wrapper',
    ppEligible: true,
    pmEligible: true,
    templateKey: 'retirement_company',
  },
  {
    id: 'perp_ancien',
    label: 'PERP (ancien)',
    grandeFamille: 'Retraite & épargne salariale',
    catalogKind: 'wrapper',
    ppEligible: true,
    pmEligible: false,
    templateKey: 'retirement_individual',
  },

  // ── Dispositifs fiscaux immobilier ───────────────────────────────────────
  {
    id: 'censi_bouvard',
    label: 'Censi-Bouvard (LMNP "réduction")',
    grandeFamille: 'Dispositifs fiscaux immobilier',
    catalogKind: 'tax_overlay',
    ppEligible: true,
    pmEligible: false,
    templateKey: 'tax_overlay_real_estate',
  },
  {
    id: 'denormandie',
    label: 'Denormandie (ancien à rénover)',
    grandeFamille: 'Dispositifs fiscaux immobilier',
    catalogKind: 'tax_overlay',
    ppEligible: true,
    pmEligible: false,
    templateKey: 'tax_overlay_real_estate',
  },
  {
    id: 'duflot',
    label: 'Duflot',
    grandeFamille: 'Dispositifs fiscaux immobilier',
    catalogKind: 'tax_overlay',
    ppEligible: true,
    pmEligible: false,
    templateKey: 'tax_overlay_real_estate',
  },
  {
    id: 'loc_avantages',
    label: 'Loc\'Avantages (convention Anah)',
    grandeFamille: 'Dispositifs fiscaux immobilier',
    catalogKind: 'tax_overlay',
    ppEligible: true,
    pmEligible: false,
    templateKey: 'tax_overlay_real_estate',
  },
  {
    id: 'louer_abordable_cosse',
    label: 'Louer abordable (Cosse) — déduction',
    grandeFamille: 'Dispositifs fiscaux immobilier',
    catalogKind: 'tax_overlay',
    ppEligible: true,
    pmEligible: false,
    templateKey: 'tax_overlay_real_estate',
  },
  {
    id: 'malraux',
    label: 'Malraux',
    grandeFamille: 'Dispositifs fiscaux immobilier',
    catalogKind: 'tax_overlay',
    ppEligible: true,
    pmEligible: false,
    templateKey: 'tax_overlay_real_estate',
  },
  {
    id: 'monuments_historiques',
    label: 'Monuments historiques',
    grandeFamille: 'Dispositifs fiscaux immobilier',
    catalogKind: 'tax_overlay',
    ppEligible: true,
    pmEligible: false,
    templateKey: 'tax_overlay_real_estate',
  },
  {
    id: 'pinel_pinel_plus',
    label: 'Pinel / Pinel+',
    grandeFamille: 'Dispositifs fiscaux immobilier',
    catalogKind: 'tax_overlay',
    ppEligible: true,
    pmEligible: false,
    templateKey: 'tax_overlay_real_estate',
  },
  {
    id: 'relance_logement_jeanbrun',
    label: 'Relance logement (dit "Jeanbrun")',
    grandeFamille: 'Dispositifs fiscaux immobilier',
    catalogKind: 'tax_overlay',
    ppEligible: true,
    pmEligible: false,
    templateKey: 'tax_overlay_real_estate',
  },
  {
    id: 'scellier',
    label: 'Scellier',
    grandeFamille: 'Dispositifs fiscaux immobilier',
    catalogKind: 'tax_overlay',
    ppEligible: true,
    pmEligible: false,
    templateKey: 'tax_overlay_real_estate',
  },

  // ── Immobilier direct ────────────────────────────────────────────────────
  {
    id: 'residence_principale',
    label: 'Résidence principale',
    grandeFamille: 'Immobilier direct',
    catalogKind: 'asset',
    ppEligible: true,
    pmEligible: false,
    templateKey: 'real_estate_direct',
  },
  {
    id: 'residence_secondaire',
    label: 'Résidence secondaire',
    grandeFamille: 'Immobilier direct',
    catalogKind: 'asset',
    ppEligible: true,
    pmEligible: false,
    templateKey: 'real_estate_direct',
  },
  {
    id: 'locatif_nu',
    label: 'Immobilier locatif nu (revenus fonciers)',
    grandeFamille: 'Immobilier direct',
    catalogKind: 'asset',
    ppEligible: true,
    pmEligible: true,
    templateKey: 'real_estate_direct',
  },
  {
    id: 'locatif_meuble_lmnp',
    label: 'Immobilier locatif meublé (LMNP)',
    grandeFamille: 'Immobilier direct',
    catalogKind: 'asset',
    ppEligible: true,
    pmEligible: false,
    templateKey: 'real_estate_direct',
  },
  {
    id: 'locatif_meuble_lmp',
    label: 'Immobilier locatif meublé (LMP)',
    grandeFamille: 'Immobilier direct',
    catalogKind: 'asset',
    ppEligible: true,
    pmEligible: false,
    templateKey: 'real_estate_direct',
  },
  {
    id: 'immobilier_garage_parking',
    label: 'Garage / parking / lot annexe',
    grandeFamille: 'Immobilier direct',
    catalogKind: 'asset',
    ppEligible: true,
    pmEligible: true,
    templateKey: 'real_estate_direct',
  },
  {
    id: 'immobilier_terrain',
    label: 'Terrain (constructible / non constructible)',
    grandeFamille: 'Immobilier direct',
    catalogKind: 'asset',
    ppEligible: true,
    pmEligible: true,
    templateKey: 'real_estate_direct',
  },

  // ── Immobilier indirect ──────────────────────────────────────────────────
  {
    id: 'groupement_foncier_agri_viti',
    label: 'Groupement foncier agricole / viticole (GFA / GFV)',
    grandeFamille: 'Immobilier indirect',
    catalogKind: 'asset',
    ppEligible: true,
    pmEligible: true,
    templateKey: 'real_estate_indirect',
  },
  {
    id: 'groupement_foncier_forestier',
    label: 'Groupement forestier (GFF / GF)',
    grandeFamille: 'Immobilier indirect',
    catalogKind: 'asset',
    ppEligible: true,
    pmEligible: true,
    templateKey: 'real_estate_indirect',
  },
  {
    id: 'parts_scpi',
    label: 'Parts de SCPI',
    grandeFamille: 'Immobilier indirect',
    catalogKind: 'asset',
    ppEligible: true,
    pmEligible: true,
    templateKey: 'scpi',
  },

  // ── Valeurs mobilières ───────────────────────────────────────────────────
  {
    id: 'fcpr',
    label: 'FCPR (fonds commun de placement à risques)',
    grandeFamille: 'Valeurs mobilières',
    catalogKind: 'asset',
    ppEligible: true,
    pmEligible: true,
    templateKey: 'fund_opc',
  },
  {
    id: 'fcpi',
    label: 'FCPI',
    grandeFamille: 'Valeurs mobilières',
    catalogKind: 'asset',
    ppEligible: true,
    pmEligible: true,
    templateKey: 'fund_opc',
  },
  {
    id: 'fip',
    label: 'FIP',
    grandeFamille: 'Valeurs mobilières',
    catalogKind: 'asset',
    ppEligible: true,
    pmEligible: true,
    templateKey: 'fund_opc',
  },
  {
    id: 'opci_grand_public',
    label: 'OPCI grand public',
    grandeFamille: 'Valeurs mobilières',
    catalogKind: 'asset',
    ppEligible: true,
    pmEligible: true,
    templateKey: 'fund_opc',
  },
  {
    id: 'actions_cotees',
    label: 'Actions (cotées)',
    grandeFamille: 'Valeurs mobilières',
    catalogKind: 'asset',
    ppEligible: true,
    pmEligible: true,
    templateKey: 'listed_securities',
  },
  {
    id: 'actions_preference',
    label: 'Actions de préférence',
    grandeFamille: 'Valeurs mobilières',
    catalogKind: 'asset',
    ppEligible: true,
    pmEligible: true,
    templateKey: 'listed_securities',
  },
  {
    id: 'parts_sociales_cooperatives',
    label: 'Parts sociales (banques mutualistes / coopératives)',
    grandeFamille: 'Valeurs mobilières',
    catalogKind: 'asset',
    ppEligible: true,
    pmEligible: true,
    templateKey: 'listed_securities',
  },
  {
    id: 'titres_participatifs',
    label: 'Titres participatifs',
    grandeFamille: 'Valeurs mobilières',
    catalogKind: 'asset',
    ppEligible: true,
    pmEligible: true,
    templateKey: 'listed_securities',
  },
  {
    id: 'droits_bsa_dps',
    label: 'Bon de souscription d\'actions / Droits / DPS',
    grandeFamille: 'Valeurs mobilières',
    catalogKind: 'asset',
    ppEligible: true,
    pmEligible: true,
    templateKey: 'listed_securities',
  },

  // ── Non coté / Private Equity ────────────────────────────────────────────
  {
    id: 'actions_non_cotees',
    label: 'Actions non cotées (parts/actions de société)',
    grandeFamille: 'Non coté/PE',
    catalogKind: 'asset',
    ppEligible: true,
    pmEligible: true,
    templateKey: 'private_equity',
  },
  {
    id: 'crowdfunding',
    label: 'Crowdfunding (actions/obligations via plateforme)',
    grandeFamille: 'Non coté/PE',
    catalogKind: 'asset',
    ppEligible: true,
    pmEligible: true,
    templateKey: 'private_equity',
  },
  {
    id: 'obligations_non_cotees',
    label: 'Obligations non cotées (PME, club deals)',
    grandeFamille: 'Non coté/PE',
    catalogKind: 'liability',
    ppEligible: true,
    pmEligible: true,
    templateKey: 'private_debt',
  },
  {
    id: 'sofica',
    label: 'SOFICA',
    grandeFamille: 'Non coté/PE',
    catalogKind: 'asset',
    ppEligible: true,
    pmEligible: true,
    templateKey: 'tax_incentive_fund',
  },
  {
    id: 'ir_pme_madelin',
    label: 'Souscription au capital de PME (IR-PME / "Madelin")',
    grandeFamille: 'Non coté/PE',
    catalogKind: 'asset',
    ppEligible: true,
    pmEligible: true,
    templateKey: 'tax_incentive_equity',
  },

  // ── Créances / Droits ────────────────────────────────────────────────────
  {
    id: 'compte_courant_associe',
    label: 'Compte courant d\'associé (créance)',
    grandeFamille: 'Créances/Droits',
    catalogKind: 'liability',
    ppEligible: true,
    pmEligible: true,
    templateKey: 'claim_right',
  },
  {
    id: 'pret_entre_particuliers',
    label: 'Prêt entre particuliers (reconnaissance de dette)',
    grandeFamille: 'Créances/Droits',
    catalogKind: 'liability',
    ppEligible: true,
    pmEligible: false,
    templateKey: 'claim_right',
  },
  {
    id: 'usufruit_nue_propriete',
    label: 'Usufruit / nue-propriété (droits patrimoniaux)',
    grandeFamille: 'Créances/Droits',
    catalogKind: 'asset',
    ppEligible: true,
    pmEligible: true,
    templateKey: 'claim_right',
  },

  // ── Autres ───────────────────────────────────────────────────────────────
  {
    id: 'crypto_actifs',
    label: 'Crypto-actifs',
    grandeFamille: 'Autres',
    catalogKind: 'asset',
    ppEligible: true,
    pmEligible: true,
    templateKey: 'crypto_asset',
  },
  {
    id: 'metaux_precieux',
    label: 'Métaux précieux',
    grandeFamille: 'Autres',
    catalogKind: 'asset',
    ppEligible: true,
    pmEligible: true,
    templateKey: 'precious_metals',
  },
  {
    id: 'tontine',
    label: 'Tontine (association tontinière)',
    grandeFamille: 'Autres',
    catalogKind: 'wrapper',
    ppEligible: true,
    pmEligible: true,
    templateKey: null,
  },
];

export const CATALOG_BY_ID: Readonly<Record<string, CatalogProduct>> =
  Object.fromEntries(CATALOG.map((p) => [p.id, p]));

export function getCatalogProduct(id: string): CatalogProduct | undefined {
  return CATALOG_BY_ID[id];
}
