import type { MementoEntry } from './types';

export const MEMENTO_FISCALITE_FOYER_ENTRIES = [
  {
    chapterId: 'fiscalite-foyer',
    key: 'fiscalite-foyer.ir',
    label: 'Impôt sur le revenu du foyer',
    description:
      'Barème progressif, quotient familial, décote, contributions sur hauts revenus et part IR du PFU administrés dans le mémento et consommés via la chaîne fiscale.',
    status: 'couvert',
    statusReason:
      'Paramètres administrés dans la section Fiscalité du foyer, sourcés via settings-references ; simulateur IR actif.',
    priority: 'critique',
    ownerPagePath: '/settings/memento',
    registryKeys: [
      'impots.ir.bareme',
      'impots.ir.abattements-et-decote',
      'impots.cehr',
      'impots.cdhr',
      'impots.pfu.part-ir',
    ],
    claimKeys: [
      'income-tax-scale-current',
      'income-tax-decote-current',
      'quotient-familial-plafond-current',
      'income-tax-dom-abatement-current',
      'abat10-salaries-current',
      'abat10-pensions-current',
      'cehr-current',
      'cdhr-current',
      'pfu-ir-current',
    ],
    refIds: [
      'cgi-193-197',
      'cgi-197',
      'cgi-200-a',
      'cgi-223-sexies',
      'boi-ir-liq-20-10',
      'boi-ir-liq-20-20-20',
      'boi-ir-liq-20-20-30',
      'boi-ir-liq-20-30-10',
      'boi-ir-chr',
    ],
    coverageSources: ['cadrage-externe'],
    relatedSimulatorIds: ['ir'],
  },
  {
    chapterId: 'fiscalite-foyer',
    key: 'fiscalite-foyer.niches-fiscales',
    label: 'Niches fiscales et réductions d’impôt',
    description:
      'Réductions et crédits d’impôt du foyer recensés par le BOFiP RICI, sans référentiel centralisé des dispositifs dans Settings.',
    status: 'partiel',
    statusReason:
      'Seuls les montants saisis manuellement dans le simulateur IR sont reflétés ; aucun paramètre dédié n’est centralisé dans le registry settings.',
    priority: 'utile',
    ownerPagePath: '/settings/memento',
    registryKeys: [],
    claimKeys: [],
    refIds: ['boi-ir-rici', 'boi-ir-rici-200', 'cgi-200-0-a'],
    coverageSources: ['cadrage-externe'],
    relatedSimulatorIds: [],
  },
  {
    chapterId: 'fiscalite-foyer',
    key: 'fiscalite-foyer.ifi',
    label: 'IFI',
    description:
      'Imposition de la fortune immobilière : barème administré dans le mémento, biens imposables et dettes lus par les analyses patrimoniales.',
    status: 'partiel',
    statusReason:
      'Barème courant administré et sourcé ; millésimes encore planifiés côté registry, simulateur IFI non livré et valorisation du démembrement fondée par le barème usufruit commun.',
    priority: 'structurant',
    ownerPagePath: '/settings/memento',
    registryKeys: ['impots.ifi.bareme', 'impots.ifi.millesimes'],
    claimKeys: ['ifi-current'],
    refIds: [
      'cgi-964',
      'cgi-972',
      'cgi-974',
      'cgi-977',
      'cgi-979',
      'cgi-669',
      'boi-pat-ifi-40-10',
      'base-source-art-973-cgi-ifi-abattement-residence-principale',
    ],
    coverageSources: ['cadrage-externe'],
    relatedSimulatorIds: ['ifi'],
  },
  {
    chapterId: 'fiscalite-foyer',
    key: 'fiscalite-foyer.non-residents',
    label: 'Fiscalité des non-résidents',
    description:
      'Imposition des revenus de source française et de la fortune immobilière des non-résidents, sous réserve des conventions fiscales.',
    status: 'partiel',
    statusReason:
      'Taux minimum, retenues à la source et champ IFI des non-résidents sourcés ; conventions fiscales et cas fins non couverts.',
    priority: 'structurant',
    ownerPagePath: '/settings/memento',
    registryKeys: [],
    claimKeys: [],
    refIds: ['cgi-197-a', 'cgi-182-a', 'cgi-187', 'cgi-964'],
    coverageSources: ['cadrage-externe'],
    relatedSimulatorIds: ['ifi'],
  },
] as const satisfies readonly MementoEntry[];
