import type { MementoEntry } from './types';

export const MEMENTO_PLACEMENTS_ENTRIES = [
  {
    chapterId: 'placements',
    key: 'placements.allocation',
    label: 'Allocation et choix d’enveloppes',
    description:
      'Comparaison d’enveloppes du simulateur placement sur les phases d’épargne, de liquidation et de transmission, adossée aux blocs du catalogue Base-Contrat.',
    status: 'couvert',
    statusReason:
      'Simulateur placement actif ; les enveloppes comparées sont documentées par les claims Base-Contrat, la fiscalité transverse étant portée par l’entrée dédiée aux prélèvements sociaux et au PFU.',
    priority: 'critique',
    ownerPagePath: '/settings/base-contrat',
    registryKeys: [],
    claimKeys: [
      'base-contrat-assurance-vie-pp-constitution-versements',
      'base-contrat-pea-pp-constitution-versements-et-titres-eligibles',
      'base-contrat-cto-pp-pp-constitution-ouverture-et-versements',
    ],
    refIds: [],
    coverageSources: ['cadrage-externe'],
    relatedSimulatorIds: ['placement'],
  },
  {
    chapterId: 'placements',
    key: 'placements.ps-pfu-revenus-capital',
    label: 'Prélèvements sociaux et PFU sur les revenus du capital',
    description:
      'Prélèvements sociaux du patrimoine et prélèvement forfaitaire unique appliqués aux revenus des enveloppes financières, consommés par les moteurs via la chaîne fiscale.',
    status: 'couvert',
    statusReason:
      'Taux administrés et sourcés via les claims settings-references des pages Prélèvements et Impôts ; la part sociale du PFU est composée depuis les prélèvements sociaux.',
    priority: 'critique',
    ownerPagePath: '/settings/prelevements',
    registryKeys: ['impots.ps-patrimoine', 'impots.pfu.part-ir'],
    claimKeys: ['patrimony-current', 'pfu-ir-current'],
    refIds: [
      'css-l136-6',
      'css-l136-7',
      'css-l136-8',
      'service-public-ps-revenus-capital-2026',
      'cgi-200-a',
    ],
    coverageSources: ['cadrage-externe'],
    relatedSimulatorIds: ['placement'],
  },
  {
    chapterId: 'placements',
    key: 'placements.assurance-vie-capitalisation',
    label: 'Assurance-vie et contrats de capitalisation',
    description:
      'Enveloppes vie et capitalisation du catalogue Base-Contrat : versements, rachats selon l’ancienneté du contrat et transmissibilité, l’angle décès restant porté par la page DMTG & Succession.',
    status: 'partiel',
    statusReason:
      'Claims Base-Contrat de constitution, de rachat et de transmission présents ; le pack placement complet reste partiel dans le registry settings.',
    priority: 'critique',
    ownerPagePath: '/settings/base-contrat',
    registryKeys: ['placements.assurance-vie-capitalisation'],
    claimKeys: [
      'base-contrat-assurance-vie-pp-constitution-versements',
      'base-contrat-assurance-vie-pp-sortie-contrat-de-moins-de-8-ans',
      'base-contrat-assurance-vie-pp-sortie-contrat-de-8-ans-et-plus',
      'base-contrat-assurance-vie-pp-sortie-anciens-contrats-regimes-anterieurs-a-1997',
      'base-contrat-assurance-vie-pp-deces-capital-hors-succession',
      'base-contrat-contrat-capitalisation-pp-pp-constitution-versements',
      'base-contrat-contrat-capitalisation-pp-pp-sortie-fiscalite-des-gains-meme-regime-que-l-assurance-vie',
      'base-contrat-contrat-capitalisation-pp-pp-deces-avantages-de-transmissibilite',
    ],
    refIds: [
      'base-source-art-125-0-a-cgi',
      'base-source-art-l132-12-code-des-assurances',
      'base-source-service-public-fonctionnement-assurance-vie',
    ],
    coverageSources: ['cadrage-externe'],
    relatedSimulatorIds: ['placement'],
  },
  {
    chapterId: 'placements',
    key: 'placements.enveloppes-titres',
    label: 'Enveloppes titres : PEA, PEA-PME et compte-titres',
    description:
      'Sous-types titres du simulateur placement : éligibilité et versements des plans, retraits selon la maturité du plan et imposition des revenus et cessions du compte-titres.',
    status: 'partiel',
    statusReason:
      'Claims Base-Contrat des plans et du compte-titres présents ; les abattements de détention des titres acquis avant la réforme du prélèvement forfaitaire restent à qualifier.',
    priority: 'structurant',
    ownerPagePath: '/settings/base-contrat',
    registryKeys: [],
    claimKeys: [
      'base-contrat-pea-pp-constitution-versements-et-titres-eligibles',
      'base-contrat-pea-pp-sortie-avant-5-ans',
      'base-contrat-pea-pp-sortie-apres-5-ans',
      'base-contrat-pea-pp-deces-cloture-et-succession',
      'base-contrat-pea-pme-pp-constitution-versements-et-titres-eligibles',
      'base-contrat-cto-pp-pp-constitution-ouverture-et-versements',
      'base-contrat-cto-pp-pp-sortie-plus-values-et-cessions',
      'base-contrat-cto-pp-pp-sortie-dividendes-et-revenus',
    ],
    refIds: [
      'base-source-art-l221-30-code-monetaire-et-financier-pea',
      'base-source-art-l221-32-1-code-monetaire-et-financier-pea-pme',
      'base-source-art-150-0-a-ii-2-cgi-pea',
      'base-source-art-200-a-cgi-pfu',
      'cgi-150-0-a',
      'boi-rppm-pvbmi-30-20',
    ],
    coverageSources: ['cadrage-externe'],
    relatedSimulatorIds: ['placement'],
  },
  {
    chapterId: 'placements',
    key: 'placements.epargne-reglementee',
    label: 'Épargne réglementée et livrets',
    description:
      'Livrets réglementés, épargne logement et plan d’épargne avenir climat : versements, exonérations de sortie et traitement successoral documentés par le catalogue Base-Contrat.',
    status: 'couvert',
    statusReason:
      'Produits sourcés bloc par bloc via les claims settings-references du catalogue Base-Contrat ; couverture de lecture sans moteur dédié.',
    priority: 'structurant',
    ownerPagePath: '/settings/base-contrat',
    registryKeys: [],
    claimKeys: [
      'base-contrat-livret-a-pp-constitution-versements-et-plafonds',
      'base-contrat-livret-a-pp-sortie-exoneration-totale',
      'base-contrat-ldds-pp-constitution-versements-et-plafonds',
      'base-contrat-lep-pp-constitution-versements-et-plafonds',
      'base-contrat-livret-jeune-pp-constitution-versements-et-plafonds',
      'base-contrat-pel-pp-constitution-versements',
      'base-contrat-pel-pp-sortie-fiscalite-des-interets',
      'base-contrat-cel-pp-constitution-versements',
      'base-contrat-peac-pp-constitution-versements-et-plafonds',
    ],
    refIds: [
      'cmf-l221-1',
      'cmf-l221-13',
      'cmf-l221-27',
      'base-source-art-157-7-cgi',
      'base-source-service-public-fr-livrets-reglementes',
      'base-source-service-public-fr-plan-epargne-logement-pel',
      'base-source-service-public-fr-compte-epargne-logement-cel',
    ],
    coverageSources: ['cadrage-externe'],
    relatedSimulatorIds: [],
  },
] as const satisfies readonly MementoEntry[];
