import type { MementoEntry } from './types';

export const MEMENTO_FOYER_ENTRIES = [
  {
    chapterId: 'foyer',
    key: 'foyer.filiation',
    label: 'Filiation et branches familiales',
    description:
      'Composition familiale, enfants communs ou non et branches utiles à la dévolution et au rattachement du dossier central.',
    status: 'planned',
    statusReason:
      'Simulateur filiation planifié ; le dossier central porte la composition familiale sans moteur dédié.',
    priority: 'critique',
    ownerPagePath: null,
    registryKeys: [],
    claimKeys: [],
    refIds: ['code-civil-757'],
    coverageSources: ['cadrage-externe'],
    relatedSimulatorIds: ['filiation'],
  },
  {
    chapterId: 'foyer',
    key: 'foyer.budget',
    label: 'Budget et capacité d’épargne',
    description:
      'Revenus, charges et capacité d’épargne du foyer comme données de dossier, sans règle fiscale propre.',
    status: 'planned',
    statusReason:
      'Simulateur budget planifié ; aucune source officielle requise car le thème ne porte pas de règle fiscale.',
    priority: 'structurant',
    ownerPagePath: null,
    registryKeys: [],
    claimKeys: [],
    refIds: [],
    coverageSources: ['cadrage-externe'],
    relatedSimulatorIds: ['budget'],
  },
  {
    chapterId: 'civil',
    key: 'civil.regime-matrimonial',
    label: 'Régime matrimonial et protection du conjoint',
    description:
      'Régimes matrimoniaux, PACS, avantages matrimoniaux et protection du conjoint survivant en lien avec les règles de transmission.',
    status: 'partiel',
    statusReason:
      'Référentiel civil des régimes matrimoniaux, du PACS et des avantages matrimoniaux affiché en lecture seule dans le mémento ; le simulateur dédié reste planifié.',
    priority: 'critique',
    ownerPagePath: '/settings/memento',
    registryKeys: [],
    claimKeys: [],
    refIds: [
      'code-civil-265',
      'code-civil-1515',
      'code-civil-1516',
      'code-civil-1518',
      'code-civil-1519',
      'code-civil-1520',
      'code-civil-1521',
      'code-civil-1524',
      'code-civil-1525',
      'code-civil-1527',
      'code-civil-1094-1',
      'cgi-796-0-bis',
    ],
    coverageSources: ['cadrage-externe'],
    relatedSimulatorIds: ['regime-matrimonial'],
  },
  {
    chapterId: 'civil',
    key: 'civil.devolution-conjoint-survivant',
    label: 'Dévolution et droits du conjoint survivant',
    description:
      'Ordres d’héritiers, options légales du conjoint survivant et donation au dernier vivant appliqués lors de la liquidation successorale.',
    status: 'partiel',
    statusReason:
      'Le moteur succession actif applique la dévolution et les options du conjoint avec les références civiles existantes ; les ordres complets hors conjoint restent à sourcer.',
    priority: 'critique',
    ownerPagePath: '/settings/memento',
    registryKeys: [],
    claimKeys: [],
    refIds: ['code-civil-720', 'code-civil-757', 'code-civil-1094-1'],
    coverageSources: ['cadrage-externe'],
    relatedSimulatorIds: ['succession'],
  },
  {
    chapterId: 'civil',
    key: 'civil.reserve-quotite',
    label: 'Réserve héréditaire et quotité disponible',
    description:
      'Parts réservées aux héritiers et quotité disponible selon la composition familiale, affichées dans le mémento et appliquées par le moteur succession.',
    status: 'couvert',
    statusReason:
      'Référentiel affiché en lecture seule et appliqué par le simulateur succession actif ; les articles du Code civil fondent la réserve, la quotité et la réduction des libéralités.',
    priority: 'critique',
    ownerPagePath: '/settings/memento',
    registryKeys: [],
    claimKeys: [],
    refIds: ['code-civil-912', 'code-civil-913', 'code-civil-920', 'code-civil-922'],
    coverageSources: ['cadrage-externe'],
    relatedSimulatorIds: ['succession'],
  },
  {
    chapterId: 'transmission',
    key: 'transmission.donations-anterieures',
    label: 'Donations antérieures',
    description:
      'Historique des donations, rapport civil et rappel fiscal pris en compte avant toute nouvelle transmission.',
    status: 'planned',
    statusReason:
      'Simulateur donations antérieures planifié ; le rappel fiscal et ses paramètres restent portés par le mémento.',
    priority: 'critique',
    ownerPagePath: '/settings/memento',
    registryKeys: [],
    claimKeys: [],
    refIds: ['cgi-784', 'code-civil-843'],
    coverageSources: ['cadrage-externe'],
    relatedSimulatorIds: ['donations-anterieures'],
  },
  {
    chapterId: 'patrimoine',
    key: 'patrimoine.demembrement',
    label: 'Démembrement de propriété',
    description:
      'Socle transversal usufruit et nue-propriété : principes civils, barème fiscal de valorisation et applications patrimoniales, consommés par la succession et les analyses de détention.',
    status: 'couvert',
    statusReason:
      'Barème de valorisation administré dans le mémento via le claim settings dédié ; principes civils fondés par le Code civil et la doctrine BOFiP.',
    priority: 'critique',
    ownerPagePath: '/settings/memento',
    registryKeys: ['transmission.dmtg-succession'],
    claimKeys: ['usufruit-nue-propriete-cgi-669'],
    refIds: ['code-civil-578', 'cgi-669', 'boi-enr-dmtg-10-40-10-50'],
    coverageSources: ['cadrage-externe'],
    relatedSimulatorIds: ['succession'],
  },
  {
    chapterId: 'patrimoine',
    key: 'patrimoine.actif-passif',
    label: 'Synthèse actif-passif',
    description:
      'Masses patrimoniales, dettes et démembrement rattachés au dossier central pour alimenter les simulateurs.',
    status: 'a_verifier',
    statusReason:
      'Étape interne du dossier sans moteur autonome ; périmètre et sources à confirmer avant toute couverture.',
    priority: 'critique',
    ownerPagePath: null,
    registryKeys: [],
    claimKeys: [],
    refIds: ['code-civil-578'],
    coverageSources: ['cadrage-externe'],
    relatedSimulatorIds: ['actif-passif'],
  },
] as const satisfies readonly MementoEntry[];
