import type { MementoEntry } from './types';

export const MEMENTO_IMMOBILIER_ENTRIES = [
  {
    chapterId: 'immobilier',
    key: 'immobilier.credit',
    label: 'Crédit et garanties',
    description:
      'Financement à crédit du patrimoine : échéancier, assurance emprunteur et garanties portés par le simulateur crédit.',
    status: 'couvert',
    statusReason:
      'Simulateur crédit actif ; le champ du crédit immobilier et les obligations de l’assuré sont fondés par les références Code de la consommation et Code des assurances.',
    priority: 'structurant',
    ownerPagePath: null,
    registryKeys: [],
    claimKeys: [],
    refIds: ['code-consommation-l313-1', 'code-assurances-l113-2'],
    coverageSources: ['cadrage-externe'],
    relatedSimulatorIds: ['credit'],
  },
  {
    chapterId: 'immobilier',
    key: 'immobilier.revenus-fonciers',
    label: 'Revenus fonciers',
    description:
      'Location nue du foyer : micro-foncier, régime réel, intérêts d’emprunt et déficit foncier rattachés au mémento.',
    status: 'planned',
    statusReason:
      'Moteur revenus fonciers planifié ; le paramètre micro-foncier reste planned dans le registry settings.',
    priority: 'structurant',
    ownerPagePath: '/settings/memento',
    registryKeys: ['immobilier.revenus-fonciers.micro-foncier'],
    claimKeys: [],
    refIds: [
      'base-source-art-28-cgi-revenus-fonciers',
      'base-source-bofip-rfpi-interets-et-frais-d-emprunt',
    ],
    coverageSources: ['cadrage-externe'],
    relatedSimulatorIds: ['revenus-fonciers'],
  },
  {
    chapterId: 'immobilier',
    key: 'immobilier.lmnp-lmp',
    label: 'Location meublée LMNP / LMP',
    description:
      'Location meublée non professionnelle et professionnelle : régimes d’imposition et bascule de statut social du loueur professionnel.',
    status: 'planned',
    statusReason:
      'Moteur location meublée planifié ; les régimes restent planned dans le registry settings.',
    priority: 'structurant',
    ownerPagePath: '/settings/memento',
    registryKeys: ['immobilier.lmnp-lmp.regimes'],
    claimKeys: [],
    refIds: ['boi-bic-champ-40', 'base-source-urssaf-lmp-cotisations-sociales'],
    coverageSources: ['cadrage-externe'],
    relatedSimulatorIds: ['lmnp-lmp'],
  },
  {
    chapterId: 'immobilier',
    key: 'immobilier.pv-immobilieres',
    label: 'Plus-values immobilières',
    description:
      'Cession immobilière des particuliers : durée de détention, exonérations et prélèvements sociaux. Le régime relève de l’article 150 U du CGI.',
    status: 'planned',
    statusReason:
      'Moteur plus-values immobilières planifié ; le paramètre de durée de détention reste planned dans le registry settings.',
    priority: 'structurant',
    ownerPagePath: '/settings/memento',
    registryKeys: ['immobilier.pv-immobilieres.abattements-duree'],
    claimKeys: [],
    refIds: [
      'base-source-art-150-u-cgi-plus-values-immobilieres',
      'boi-rfpi-pvi-10',
      'boi-rfpi-pvi-20',
    ],
    coverageSources: ['cadrage-externe'],
    relatedSimulatorIds: ['plus-values-immobilieres'],
  },
  {
    chapterId: 'immobilier',
    key: 'immobilier.scpi',
    label: 'SCPI',
    description:
      'Parts de SCPI comme sous-parcours du placement, détenues par une personne physique ou morale : souscription, revenus, cession et transmission documentés par le catalogue Base-Contrat.',
    status: 'partiel',
    statusReason:
      'Enveloppe documentée en lecture par les claims Base-Contrat pour les détentions physique et morale ; le simulateur SCPI et son pack fiscal dédié restent planifiés dans le registry settings.',
    priority: 'structurant',
    ownerPagePath: '/settings/memento',
    registryKeys: ['immobilier.scpi.regime'],
    claimKeys: [
      'base-contrat-parts-scpi-pp-pp-constitution-souscription-et-revenus',
      'base-contrat-parts-scpi-pp-pp-sortie-plus-value-de-cession',
      'base-contrat-parts-scpi-pp-pp-deces-succession',
      'base-contrat-parts-scpi-pm-pm-constitution-souscription-et-revenus-personne-morale',
      'base-contrat-parts-scpi-pm-pm-sortie-cession-des-parts',
      'base-contrat-parts-scpi-pm-pm-deces-fin-de-vie-sortie-de-la-pm',
    ],
    refIds: [
      'base-source-art-28-cgi-revenus-fonciers',
      'base-source-art-150-u-cgi-plus-values-immobilieres',
      'boi-rfpi-pvi-10',
      'boi-rfpi-pvi-20',
    ],
    coverageSources: ['cadrage-externe'],
    relatedSimulatorIds: ['scpi'],
  },
  {
    chapterId: 'immobilier',
    key: 'immobilier.investissement-locatif',
    label: 'Investissement locatif',
    description:
      'Projet locatif du foyer : croisement du financement, des régimes fonciers ou meublés et de la fiscalité du bien mis en location.',
    status: 'planned',
    statusReason:
      'Simulateur investissement locatif planifié ; les régimes fonciers et meublés consommés restent planned dans le registry settings.',
    priority: 'structurant',
    ownerPagePath: '/settings/memento',
    registryKeys: ['immobilier.revenus-fonciers.micro-foncier', 'immobilier.lmnp-lmp.regimes'],
    claimKeys: [],
    refIds: ['base-source-art-28-cgi-revenus-fonciers'],
    coverageSources: ['cadrage-externe'],
    relatedSimulatorIds: ['investissement-locatif'],
  },
  {
    chapterId: 'immobilier',
    key: 'immobilier.dispositifs-fiscaux',
    label: 'Dispositifs fiscaux immobiliers',
    description:
      'Dispositifs de défiscalisation immobilière du catalogue Base-Contrat : Censi-Bouvard, Denormandie, Duflot, Loc’Avantages, Cosse, Malraux, Monuments historiques, Pinel, Relance logement Jeanbrun et Scellier, sur les phases de constitution, de cession et de transmission.',
    status: 'partiel',
    statusReason:
      'Dispositifs sourcés un par un via les claims du catalogue Base-Contrat ; aucun moteur ni paramètre administré, les conditions fines restent à qualifier avant tout calcul.',
    priority: 'utile',
    ownerPagePath: '/settings/memento',
    registryKeys: [],
    claimKeys: [
      'base-contrat-censi-bouvard-pp-constitution-reduction-ou-deduction-d-ir',
      'base-contrat-censi-bouvard-pp-sortie-cession',
      'base-contrat-censi-bouvard-pp-deces-succession',
      'base-contrat-denormandie-pp-constitution-reduction-d-ir-ancien-a-renover',
      'base-contrat-denormandie-pp-sortie-cession-du-bien',
      'base-contrat-denormandie-pp-deces-succession',
      'base-contrat-duflot-pp-constitution-reduction-ou-deduction-d-ir',
      'base-contrat-duflot-pp-sortie-cession',
      'base-contrat-duflot-pp-deces-succession',
      'base-contrat-loc-avantages-pp-constitution-reduction-ou-deduction-d-ir',
      'base-contrat-loc-avantages-pp-sortie-cession',
      'base-contrat-loc-avantages-pp-deces-succession',
      'base-contrat-louer-abordable-cosse-pp-constitution-reduction-ou-deduction-d-ir',
      'base-contrat-louer-abordable-cosse-pp-sortie-cession',
      'base-contrat-louer-abordable-cosse-pp-deces-succession',
      'base-contrat-malraux-pp-constitution-reduction-d-ir-restauration-de-patrimoine',
      'base-contrat-malraux-pp-sortie-cession',
      'base-contrat-malraux-pp-deces-succession',
      'base-contrat-monuments-historiques-pp-constitution-deduction-des-charges-regime-de-faveur',
      'base-contrat-monuments-historiques-pp-sortie-cession',
      'base-contrat-monuments-historiques-pp-deces-succession-avantage-dmtg',
      'base-contrat-pinel-pinel-plus-pp-constitution-reduction-d-ir-dispositif-cloture-au-31-12-2024',
      'base-contrat-pinel-pinel-plus-pp-sortie-cession-du-bien',
      'base-contrat-pinel-pinel-plus-pp-deces-succession',
      'base-contrat-relance-logement-jeanbrun-pp-constitution-reduction-ou-deduction-d-ir',
      'base-contrat-relance-logement-jeanbrun-pp-sortie-cession',
      'base-contrat-relance-logement-jeanbrun-pp-deces-succession',
      'base-contrat-scellier-pp-constitution-reduction-ou-deduction-d-ir',
      'base-contrat-scellier-pp-sortie-cession',
      'base-contrat-scellier-pp-deces-succession',
    ],
    refIds: [
      'base-source-art-199-tervicies-cgi-malraux',
      'base-source-art-156-bis-cgi-monuments-historiques',
      'base-source-art-795-a-cgi-exoneration-dmtg-monuments-historiques',
      'base-source-art-199-novovicies-cgi-denormandie',
    ],
    coverageSources: ['cadrage-externe'],
    relatedSimulatorIds: ['investissement-locatif'],
  },
  {
    chapterId: 'immobilier',
    key: 'immobilier.sci',
    label: 'SCI et mode de détention',
    description:
      'Détention immobilière via une société civile : choix du mode de détention, fonctionnement et transmission des parts.',
    status: 'planned',
    statusReason:
      'Simulateur SCI planifié ; les règles de détention, de translucidité fiscale et de transmission de parts restent à qualifier avec le socle société.',
    priority: 'structurant',
    ownerPagePath: '/settings/memento',
    registryKeys: [],
    claimKeys: [],
    refIds: ['code-civil-1075'],
    coverageSources: ['cadrage-externe'],
    relatedSimulatorIds: ['sci'],
  },
  {
    chapterId: 'immobilier',
    key: 'immobilier.non-residents',
    label: 'Immobilier des non-résidents',
    description:
      'Cessions et revenus immobiliers de source française des non-résidents, dépendants de l’affiliation sociale et des conventions fiscales.',
    status: 'a_verifier',
    statusReason:
      'Aucun claim ni référence repo sur ce périmètre ; les règles doivent être qualifiées sur une source officielle avant tout affichage opérationnel.',
    priority: 'structurant',
    ownerPagePath: '/settings/memento',
    registryKeys: [],
    claimKeys: [],
    refIds: [],
    coverageSources: ['cadrage-externe'],
    relatedSimulatorIds: ['plus-values-immobilieres'],
  },
  {
    chapterId: 'arbitrage',
    key: 'arbitrage.vendre-conserver-reemployer',
    label: 'Vendre, conserver ou réemployer',
    description:
      'Choix entre conserver, céder ou réemployer un actif : croisement de la fiscalité de cession immobilière et mobilière avec les enveloppes de réemploi.',
    status: 'planned',
    statusReason:
      'Simulateur arbitrage et réemploi planifié ; les régimes de cession sont référencés mais le moteur de comparaison reste à construire.',
    priority: 'structurant',
    ownerPagePath: '/settings/memento',
    registryKeys: [],
    claimKeys: [],
    refIds: ['cgi-150-0-a', 'base-source-art-150-u-cgi-plus-values-immobilieres'],
    coverageSources: ['cadrage-externe'],
    relatedSimulatorIds: ['arbitrage-reemploi'],
  },
] as const satisfies readonly MementoEntry[];
