import type { MementoEntry } from './types';

export const MEMENTO_SOCIETE_ENTRIES = [
  {
    chapterId: 'societe',
    key: 'societe.is',
    label: 'Impôt sur les sociétés',
    description:
      'Impôt dû par les sociétés sur leur résultat fiscal, avec distinction entre régime normal, taux réduit et règles de liquidation.',
    status: 'couvert',
    statusReason:
      'Paramètres IS administrés et sourcés via le claim settings-references ; consommés par le simulateur trésorerie société actif.',
    priority: 'critique',
    ownerPagePath: '/settings/memento',
    registryKeys: ['comptables-societes.is'],
    claimKeys: ['corporate-tax-current'],
    refIds: ['cgi-209', 'cgi-219', 'boi-is-liq-10', 'boi-is-liq-20'],
    coverageSources: ['cadrage-externe'],
    relatedSimulatorIds: ['tresorerie-societe'],
  },
  {
    chapterId: 'societe',
    key: 'societe.groupe-mere-fille-qpfc',
    label: 'Régime mère-fille et quote-part de frais et charges',
    description:
      'Remontée de dividendes intragroupe : exonération mère-fille, quote-part de frais et charges et conditions de détention.',
    status: 'partiel',
    statusReason:
      'Quote-part administrée via le claim settings IS ; éligibilité mère-fille et quote-part sont sourcées, le simulateur holding restant planifié.',
    priority: 'critique',
    ownerPagePath: '/settings/memento',
    registryKeys: ['comptables-societes.mere-fille-qpfc'],
    claimKeys: ['corporate-tax-current'],
    refIds: ['cgi-145', 'cgi-216', 'cgi-209', 'cgi-219'],
    coverageSources: ['cadrage-externe'],
    relatedSimulatorIds: ['tresorerie-societe', 'holding'],
  },
  {
    chapterId: 'societe',
    key: 'societe.compte-courant-associe',
    label: 'Comptes courants d’associés',
    description:
      'Avances des associés à la société : intérêts, remboursement, convention et déductibilité à apprécier selon les règles fiscales.',
    status: 'partiel',
    statusReason:
      'Taux maximal d’intérêts déductibles administré via le claim settings IS ; la déductibilité des intérêts est sourcée, les conventions et remboursements restant hors moteur.',
    priority: 'structurant',
    ownerPagePath: '/settings/memento',
    registryKeys: ['comptables-societes.is'],
    claimKeys: ['corporate-tax-current'],
    refIds: ['cgi-39', 'cgi-209'],
    coverageSources: ['cadrage-externe'],
    relatedSimulatorIds: ['tresorerie-societe'],
  },
  {
    chapterId: 'societe',
    key: 'societe.resultat-distribuable-reserves',
    label: 'Résultat distribuable et réserves',
    description:
      'Dotation de la réserve légale, détermination du bénéfice distribuable et décision de distribution des dividendes.',
    status: 'partiel',
    statusReason:
      'Règles fondées par les articles du Code de commerce référencés ; aucun paramètre administré ni moteur de projection livré.',
    priority: 'critique',
    ownerPagePath: '/settings/memento',
    registryKeys: [],
    claimKeys: [],
    refIds: ['code-commerce-l232-10', 'code-commerce-l232-11', 'code-commerce-l232-12'],
    coverageSources: ['cadrage-externe'],
    relatedSimulatorIds: ['projection-comptable'],
  },
  {
    chapterId: 'societe',
    key: 'societe.capitaux-propres',
    label: 'Capitaux propres et reconstitution',
    description:
      'Alerte et procédure lorsque les capitaux propres deviennent inférieurs à la moitié du capital social, pour les sociétés à responsabilité limitée et par actions.',
    status: 'partiel',
    statusReason:
      'Procédures fondées par les articles du Code de commerce référencés ; aucun paramètre administré ni moteur livré.',
    priority: 'structurant',
    ownerPagePath: '/settings/memento',
    registryKeys: [],
    claimKeys: [],
    refIds: ['code-commerce-l223-42', 'code-commerce-l225-248'],
    coverageSources: ['cadrage-externe'],
    relatedSimulatorIds: ['projection-comptable'],
  },
  {
    chapterId: 'societe',
    key: 'societe.bilans-liasses-source',
    label: 'Bilans et liasses comme sources dossier',
    description:
      'Bilans, liasses et pièces comptables comme socle de lecture du résultat, des capitaux propres et de la trésorerie.',
    status: 'planned',
    statusReason:
      'Besoin F5 inventorié ; les bilans et liasses doivent alimenter le dossier société futur, sans page de production comptable ni moteur livré.',
    priority: 'structurant',
    ownerPagePath: '/settings/memento',
    registryKeys: [],
    claimKeys: [],
    refIds: [],
    coverageSources: ['cadrage-externe'],
    relatedSimulatorIds: ['projection-comptable', 'valorisation-titres', 'tresorerie-societe'],
  },
  {
    chapterId: 'societe',
    key: 'societe.primes',
    label: 'Primes d’émission, fusion ou apport',
    description:
      'Primes inscrites dans les capitaux propres, utiles pour lire l’historique du capital et la valeur des titres.',
    status: 'planned',
    statusReason:
      'Sujet comptable F5 inventorié ; aucune source qualifiée, valeur administrée ni consommation moteur dédiée n’est livrée.',
    priority: 'utile',
    ownerPagePath: '/settings/memento',
    registryKeys: [],
    claimKeys: [],
    refIds: [],
    coverageSources: ['cadrage-externe'],
    relatedSimulatorIds: ['projection-comptable', 'valorisation-titres'],
  },
  {
    chapterId: 'societe',
    key: 'societe.emprunts',
    label: 'Emprunts société',
    description:
      'Encours, intérêts, échéancier et actif financé à rapprocher du résultat et de la trésorerie de la société.',
    status: 'planned',
    statusReason:
      'Trésorerie société consomme déjà des emprunts dans son périmètre actuel, mais le modèle bilan F5 et les sources comptables restent à qualifier.',
    priority: 'structurant',
    ownerPagePath: '/settings/memento',
    registryKeys: [],
    claimKeys: [],
    refIds: [],
    coverageSources: ['cadrage-externe'],
    relatedSimulatorIds: ['tresorerie-societe', 'projection-comptable'],
  },
  {
    chapterId: 'societe',
    key: 'societe.immobilisations',
    label: 'Immobilisations',
    description:
      'Immobilisations et amortissements éventuels comme composantes du bilan, du résultat et de la valeur économique.',
    status: 'planned',
    statusReason:
      'Besoin F5 inventorié ; aucun moteur de projection comptable ni source ANC qualifiée n’est livré dans ce lot.',
    priority: 'structurant',
    ownerPagePath: '/settings/memento',
    registryKeys: [],
    claimKeys: [],
    refIds: [],
    coverageSources: ['cadrage-externe'],
    relatedSimulatorIds: ['projection-comptable', 'valorisation-titres'],
  },
  {
    chapterId: 'societe',
    key: 'societe.immobilier-detenu',
    label: 'Immobilier détenu par la société',
    description:
      'Détention d’immobilier par une société : traitement patrimonial, fiscalité applicable et effets sur la valeur des titres.',
    status: 'planned',
    statusReason:
      'Sujet transversal F5/F3 inventorié ; le modèle actif/passif et le traitement fiscal restent à qualifier avant tout calcul.',
    priority: 'structurant',
    ownerPagePath: '/settings/memento',
    registryKeys: [],
    claimKeys: [],
    refIds: [],
    coverageSources: ['cadrage-externe'],
    relatedSimulatorIds: ['valorisation-titres', 'tresorerie-societe'],
  },
  {
    chapterId: 'societe',
    key: 'societe.tresorerie',
    label: 'Trésorerie société',
    description:
      'Projection de trésorerie d’une société patrimoniale à l’IS : flux associés, allocations et revenus distribuables.',
    status: 'partiel',
    statusReason:
      'Simulateur trésorerie société actif consommant l’IS, la quote-part mère-fille et le seuil social des dividendes TNS ; les périmètres comptables complémentaires restent planifiés.',
    priority: 'critique',
    ownerPagePath: '/settings/memento',
    registryKeys: [
      'comptables-societes.is',
      'comptables-societes.mere-fille-qpfc',
      'social-dirigeant.charges-sociales',
    ],
    claimKeys: ['corporate-tax-current', 'social-dirigeant-dividendes-tns'],
    refIds: ['cgi-38', 'cgi-209', 'cgi-219'],
    coverageSources: ['cadrage-externe'],
    relatedSimulatorIds: ['tresorerie-societe'],
  },
  {
    chapterId: 'societe',
    key: 'societe.organigramme',
    label: 'Organigramme et liens capitalistiques',
    description:
      'Formes sociales, associés et liens capitalistiques directs ou indirects comme socle du dossier société.',
    status: 'planned',
    statusReason:
      'Simulateur organigramme société planifié ; les principales formes sociales sont sourcées, mais le modèle capitalistique reste à construire.',
    priority: 'structurant',
    ownerPagePath: '/settings/memento',
    registryKeys: [],
    claimKeys: [],
    refIds: [
      'code-commerce-l210-1',
      'code-commerce-l223-1',
      'code-commerce-l225-1',
      'code-commerce-l227-1',
    ],
    coverageSources: ['cadrage-externe'],
    relatedSimulatorIds: ['organigramme-societe'],
  },
  {
    chapterId: 'societe',
    key: 'societe.projection-comptable',
    label: 'Projection comptable',
    description:
      'Projection du résultat, des réserves et du report à nouveau à partir des bilans et liasses comme sources du dossier société.',
    status: 'planned',
    statusReason:
      'Simulateur projection comptable planifié ; le socle distribuable et réserves est fondé par le Code de commerce sans moteur livré.',
    priority: 'structurant',
    ownerPagePath: '/settings/memento',
    registryKeys: [],
    claimKeys: [],
    refIds: ['code-commerce-l232-10', 'code-commerce-l232-11'],
    coverageSources: ['cadrage-externe'],
    relatedSimulatorIds: ['projection-comptable'],
  },
  {
    chapterId: 'societe',
    key: 'societe.valorisation-titres',
    label: 'Valorisation de titres',
    description:
      'Méthodes d’évaluation des titres de société pour les analyses patrimoniales et la préparation des transmissions.',
    status: 'planned',
    statusReason:
      'Simulateur valorisation planifié ; le guide DGFiP d’évaluation est référencé sans moteur ni méthode automatisée.',
    priority: 'structurant',
    ownerPagePath: '/settings/memento',
    registryKeys: [],
    claimKeys: [],
    refIds: ['boi-enr-dmtg-10-40', 'impots-guide-evaluation-entreprises-titres'],
    coverageSources: ['cadrage-externe'],
    relatedSimulatorIds: ['valorisation-titres'],
  },
  {
    chapterId: 'societe',
    key: 'societe.cession-titres',
    label: 'Cession de titres',
    description:
      'Cession de titres de société par le dirigeant ou les associés : plus-values mobilières et régimes particuliers.',
    status: 'partiel',
    statusReason:
      'Régime des plus-values mobilières et abattement dirigeant retraite sourcés ; le moteur de cession reste planifié au registry settings.',
    priority: 'structurant',
    ownerPagePath: '/settings/memento',
    registryKeys: ['comptables-societes.pv-mobilieres'],
    claimKeys: [],
    refIds: ['cgi-150-0-a', 'cgi-150-0-d-ter', 'boi-rppm-pvbmi-30-20'],
    coverageSources: ['cadrage-externe'],
    relatedSimulatorIds: ['cession-titres'],
  },
  {
    chapterId: 'societe',
    key: 'societe.holding-apport-cession',
    label: 'Holding et apport-cession',
    description:
      'Structuration par holding, apport de titres avant cession et réemploi du produit de cession.',
    status: 'planned',
    statusReason:
      'Pack registry planifié ; le report d’imposition de l’apport-cession est sourcé, les conditions de structuration holding restant hors moteur.',
    priority: 'critique',
    ownerPagePath: '/settings/memento',
    registryKeys: ['comptables-societes.holding-apport-cession'],
    claimKeys: [],
    refIds: ['cgi-150-0-b-ter'],
    coverageSources: ['cadrage-externe'],
    relatedSimulatorIds: ['holding', 'cession-titres'],
  },
  {
    chapterId: 'societe',
    key: 'societe.obo',
    label: 'OBO',
    description:
      'Rachat à soi-même d’une société par endettement : valorisation, financement et restructuration du capital.',
    status: 'a_verifier',
    statusReason:
      'Montage inscrit à la roadmap sans moteur ni source ; le périmètre et la méthode doivent être qualifiés sur une source officielle avant toute couverture.',
    priority: 'utile',
    ownerPagePath: '/settings/memento',
    registryKeys: [],
    claimKeys: [],
    refIds: [],
    coverageSources: ['cadrage-externe'],
    relatedSimulatorIds: [],
  },
  {
    chapterId: 'societe',
    key: 'societe.epargne-salariale',
    label: 'Épargne salariale',
    description:
      'Intéressement, participation, plans d’épargne d’entreprise et avantages employeur associés au droit du travail.',
    status: 'partiel',
    statusReason:
      'Dispositifs collectifs documentés par les claims du catalogue Base-Contrat, le Code du travail, l’URSSAF et le BOSS ; la route reste placeholder et les plafonds ne sont pas administrés.',
    priority: 'structurant',
    ownerPagePath: '/settings/memento',
    registryKeys: ['placements.epargne-salariale'],
    claimKeys: [
      'base-contrat-percol-pp-pp-constitution-versements',
      'base-contrat-percol-pp-pp-sortie-avant-5-ans-blocage',
      'base-contrat-percol-pp-pp-sortie-apres-5-ans',
    ],
    refIds: [
      'code-travail-l3312-1',
      'code-travail-l3332-1',
      'boi-rsa-es-10',
      'boi-rsa-es-10-10',
      'boi-rsa-es-10-20',
      'boss-epargne-salariale',
      'urssaf-forfait-social',
      'code-travail-l3332-15',
      'base-source-art-l3332-10-code-du-travail-pee-versements',
      'base-source-art-l3332-25-code-du-travail-pee-sortie',
      'base-source-entreprendre-service-public-participation',
    ],
    coverageSources: ['cadrage-externe'],
    relatedSimulatorIds: ['epargne-salariale'],
  },
] as const satisfies readonly MementoEntry[];
