import type { MementoEntry } from './types';

export const MEMENTO_RETRAITE_ENTRIES = [
  {
    chapterId: 'retraite',
    key: 'retraite.globale',
    label: 'Retraite globale',
    description:
      'Vue globale des droits obligatoires, de l’âge de départ, de la durée d’assurance et des régimes de base ou complémentaires.',
    status: 'planned',
    statusReason:
      'La registry expose déjà PASS, prélèvements sociaux retraite et seuils RFR ; le simulateur retraite reste planifié et aucun modèle générationnel n’est livré.',
    priority: 'critique',
    ownerPagePath: '/settings/memento',
    registryKeys: [
      'retraite-prevoyance.ps-retraite',
      'retraite-prevoyance.seuils-rfr',
      'retraite-prevoyance.pass',
      'retraite-prevoyance.cotisations-retraite',
      'retraite-prevoyance.validation-retraite-600-smic',
    ],
    claimKeys: ['retirement-current-brackets', 'retirement-thresholds-current', 'pass-latest'],
    refIds: [
      'assurance-retraite-age-taux-plein',
      'css-l351-3',
      'urssaf-pass-2026',
      'ameli-pass-2026',
    ],
    coverageSources: ['cadrage-externe'],
    relatedSimulatorIds: ['retraite'],
  },
  {
    chapterId: 'retraite',
    key: 'retraite.regime-general',
    label: 'Régime général salarié',
    description:
      'Droits obligatoires du régime général : âge, durée d’assurance, taux plein, décote, surcote et retraite de base.',
    status: 'partiel',
    statusReason:
      'La source Assurance retraite qualifie le cadrage du régime général ; SER1 ne livre pas encore de moteur de droits salariés.',
    priority: 'critique',
    ownerPagePath: '/settings/memento',
    registryKeys: ['retraite-prevoyance.pass'],
    claimKeys: ['pass-latest'],
    refIds: ['assurance-retraite-age-taux-plein', 'css-l351-3'],
    coverageSources: ['cadrage-externe'],
    relatedSimulatorIds: ['retraite'],
  },
  {
    chapterId: 'retraite',
    key: 'retraite.dispositifs-depart',
    label: 'Dispositifs de départ',
    description:
      'Départs anticipés, retraite progressive et cumul emploi-retraite à distinguer du calcul de retraite standard.',
    status: 'partiel',
    statusReason:
      'Les sources CSS et Assurance retraite qualifient les principaux dispositifs ; aucun moteur multi-carrière n’est livré.',
    priority: 'structurant',
    ownerPagePath: '/settings/memento',
    registryKeys: [
      'retraite-prevoyance.pass',
      'retraite-prevoyance.cotisations-retraite',
      'retraite-prevoyance.validation-retraite-600-smic',
    ],
    claimKeys: ['pass-latest'],
    refIds: [
      'css-l351-1-l351-17',
      'css-l161-22',
      'assurance-retraite-carriere-longue',
      'assurance-retraite-retraite-progressive',
      'assurance-retraite-cumul-emploi-retraite',
    ],
    coverageSources: ['cadrage-externe'],
    relatedSimulatorIds: ['retraite'],
  },
  {
    chapterId: 'retraite',
    key: 'retraite.decote-surcote',
    label: 'Décote et surcote',
    description:
      'Minorations et majorations de pension liées à la durée d’assurance et au choix de date de liquidation.',
    status: 'partiel',
    statusReason:
      'Les sources Assurance retraite et CSS cadrent le sujet ; SER1 ne calcule pas encore les effets par carrière.',
    priority: 'structurant',
    ownerPagePath: '/settings/memento',
    registryKeys: ['retraite-prevoyance.cotisations-retraite'],
    claimKeys: [],
    refIds: ['assurance-retraite-age-taux-plein', 'css-l351-1-l351-17'],
    coverageSources: ['cadrage-externe'],
    relatedSimulatorIds: ['retraite'],
  },
  {
    chapterId: 'retraite',
    key: 'retraite.reversion',
    label: 'Réversion',
    description:
      'Droits dérivés du conjoint survivant à intégrer aux futurs scénarios retraite et transmission.',
    status: 'partiel',
    statusReason:
      'La pension de réversion est qualifiée par les sources CSS et Assurance retraite ; le calcul des ressources reste hors lot.',
    priority: 'structurant',
    ownerPagePath: '/settings/memento',
    registryKeys: ['retraite-prevoyance.cotisations-retraite'],
    claimKeys: [],
    refIds: ['css-l353-1', 'assurance-retraite-pension-reversion'],
    coverageSources: ['cadrage-externe'],
    relatedSimulatorIds: ['retraite', 'succession'],
  },
  {
    chapterId: 'retraite',
    key: 'retraite.agirc-arrco',
    label: 'Complémentaire AGIRC-ARRCO',
    description:
      'Retraite complémentaire des salariés par points, distincte du régime général de base.',
    status: 'partiel',
    statusReason:
      'La source AGIRC-ARRCO qualifie le principe des points ; les valeurs, tranches et calculs restent hors lot.',
    priority: 'critique',
    ownerPagePath: '/settings/memento',
    registryKeys: ['retraite-prevoyance.cotisations-retraite'],
    claimKeys: [],
    refIds: ['agirc-arrco-points-retraite'],
    coverageSources: ['cadrage-externe'],
    relatedSimulatorIds: ['retraite'],
  },
  {
    chapterId: 'retraite',
    key: 'retraite.dirigeant-assimile-salarie',
    label: 'Retraite dirigeant assimilé salarié',
    description:
      'Rattachement retraite des mandataires assimilés salariés, à séparer du salarié standard et du dirigeant TNS.',
    status: 'planned',
    statusReason:
      'Les sources sociales du dirigeant et les sources retraite de base et complémentaire sont identifiées ; l’articulation rémunération-droits reste à livrer.',
    priority: 'structurant',
    ownerPagePath: '/settings/memento',
    registryKeys: [
      'social-dirigeant.charges-sociales',
      'retraite-prevoyance.cotisations-retraite',
      'retraite-prevoyance.validation-retraite-600-smic',
    ],
    claimKeys: [],
    refIds: [
      'urssaf-assimile-salarie-dirigeant',
      'assurance-retraite-age-taux-plein',
      'agirc-arrco-points-retraite',
    ],
    coverageSources: ['cadrage-externe'],
    relatedSimulatorIds: ['retraite', 'remuneration'],
  },
  {
    chapterId: 'retraite',
    key: 'retraite.ssi-artisan-commercant',
    label: 'Retraite SSI artisan et commerçant',
    description:
      'Droits retraite obligatoires des artisans, commerçants et indépendants rattachés au régime général.',
    status: 'partiel',
    statusReason:
      'Les sources Service-Public, URSSAF et CSS cadrent la retraite de l’entrepreneur individuel ; le moteur détaillé reste à construire.',
    priority: 'structurant',
    ownerPagePath: '/settings/memento',
    registryKeys: [
      'retraite-prevoyance.cotisations-retraite',
      'retraite-prevoyance.validation-retraite-600-smic',
    ],
    claimKeys: [],
    refIds: [
      'entreprendre-service-public-retraite-ei',
      'urssaf-independant-droits-retraite',
      'css-l633-1',
      'css-l635-1',
    ],
    coverageSources: ['cadrage-externe'],
    relatedSimulatorIds: ['retraite', 'remuneration'],
  },
  {
    chapterId: 'retraite',
    key: 'retraite.cnavpl-professions-liberales',
    label: 'CNAVPL et professions libérales',
    description:
      'Socle retraite des professions libérales réglementées, avec régime de base commun et régimes complémentaires par section.',
    status: 'partiel',
    statusReason:
      'Les sources CNAVPL, Service-Public et CSS qualifient le socle ; chaque section professionnelle reste à modéliser caisse par caisse.',
    priority: 'structurant',
    ownerPagePath: '/settings/memento',
    registryKeys: [
      'retraite-prevoyance.cotisations-retraite',
      'retraite-prevoyance.validation-retraite-600-smic',
    ],
    claimKeys: [],
    refIds: [
      'cnavpl-retraite-liberaux',
      'entreprendre-service-public-retraite-ei',
      'css-l641-1',
      'css-l643-1',
      'css-d643-1',
    ],
    coverageSources: ['cadrage-externe'],
    relatedSimulatorIds: ['retraite', 'remuneration'],
  },
  {
    chapterId: 'retraite',
    key: 'retraite.caisses-sante-liberales',
    label: 'Caisses santé libérales',
    description:
      'Retraite des professionnels de santé libéraux, à rattacher aux caisses professionnelles concernées.',
    status: 'partiel',
    statusReason:
      'CARMF, CARCDSF, CARPIMKO, CAVP et CARPV sont sourcées caisse par caisse ; aucun calcul de liquidation par profession n’est livré.',
    priority: 'utile',
    ownerPagePath: '/settings/memento',
    registryKeys: ['retraite-prevoyance.cotisations-retraite'],
    claimKeys: [],
    refIds: [
      'carmf-retraite',
      'carcdsf-regimes-retraite',
      'carpimko-retraite',
      'cavp-retraite',
      'carpv-statuts-retraite-prevoyance',
    ],
    coverageSources: ['cadrage-externe'],
    relatedSimulatorIds: ['retraite', 'remuneration'],
  },
  {
    chapterId: 'retraite',
    key: 'retraite.cipav',
    label: 'CIPAV',
    description:
      'Retraite des professionnels rattachés à la CIPAV, avec identification de la caisse avant modèle dédié.',
    status: 'partiel',
    statusReason:
      'La source CIPAV qualifie l’affiliation et les droits à cadrer ; les règles de liquidation et de réversion restent hors lot.',
    priority: 'utile',
    ownerPagePath: '/settings/memento',
    registryKeys: ['retraite-prevoyance.cotisations-retraite'],
    claimKeys: [],
    refIds: ['lacipav-affiliation-retraite'],
    coverageSources: ['cadrage-externe'],
    relatedSimulatorIds: ['retraite', 'remuneration'],
  },
  {
    chapterId: 'retraite',
    key: 'retraite.msa',
    label: 'MSA',
    description:
      'Retraite des salariés et exploitants agricoles, à distinguer des caisses libérales et du régime général classique.',
    status: 'partiel',
    statusReason:
      'La source MSA qualifie l’entrée retraite agricole ; le détail salarié, exploitant et règles agricoles reste à qualifier.',
    priority: 'utile',
    ownerPagePath: '/settings/memento',
    registryKeys: ['retraite-prevoyance.cotisations-retraite'],
    claimKeys: [],
    refIds: ['msa-retraite'],
    coverageSources: ['cadrage-externe'],
    relatedSimulatorIds: ['retraite'],
  },
  {
    chapterId: 'retraite',
    key: 'retraite.autres-caisses-liberales',
    label: 'Autres caisses libérales',
    description:
      'Retraite des professions libérales non santé, dont droit, conseil, assurance et officiers ministériels.',
    status: 'partiel',
    statusReason:
      'CAVEC, CAVAMAC, CNBF, CPRN et CAVOM sont sourcées ; aucun moteur ne liquide encore les régimes complémentaires par caisse.',
    priority: 'utile',
    ownerPagePath: '/settings/memento',
    registryKeys: ['retraite-prevoyance.cotisations-retraite'],
    claimKeys: [],
    refIds: [
      'cavec-retraite-complementaire',
      'cavamac-retraite',
      'cnbf-institution-retraite-prevoyance',
      'cprn-affiliation-obligatoire',
      'cavom-retraite',
    ],
    coverageSources: ['cadrage-externe'],
    relatedSimulatorIds: ['retraite', 'remuneration'],
  },
  {
    chapterId: 'retraite',
    key: 'retraite.fonction-publique',
    label: 'Fonction publique',
    description:
      'Retraite des agents publics, à séparer du régime général, des indépendants et des caisses libérales.',
    status: 'planned',
    statusReason:
      'SRE, CNRACL, IRCANTEC et RAFP sont sourcés pour le cadrage ; aucun modèle fonction publique ni réglage dédié n’est livré.',
    priority: 'utile',
    ownerPagePath: '/settings/memento',
    registryKeys: [],
    claimKeys: [],
    refIds: [
      'code-pensions-civiles-militaires-l24',
      'service-public-retraite-agent-public',
      'service-public-rafp',
      'service-public-ircantec-contractuel',
    ],
    coverageSources: ['cadrage-externe'],
    relatedSimulatorIds: ['retraite'],
  },
] as const satisfies readonly MementoEntry[];
