export const MEMENTO_INTERNATIONAL_REFERENCE_VALUES = [
  {
    key: 'non-residents-ir-premiere-fraction',
    domain: 'fiscalite-internationale',
    subdomain: 'non-residents-ir',
    label: 'IR non-résidents — première fraction',
    value_numeric: 20,
    value_text: null,
    unit: '%',
    year: 2026,
    data: { kind: 'minimum_tax_rate', scope: 'source_france_income', band: 'first' },
    ref_ids: ['cgi-197-a'],
    display_order: 3000,
    note: 'Minimum prévu par l’article 197 A.',
    updated_at: null,
  },
  {
    key: 'non-residents-ir-fraction-superieure',
    domain: 'fiscalite-internationale',
    subdomain: 'non-residents-ir',
    label: 'IR non-résidents — fraction supérieure',
    value_numeric: 30,
    value_text: null,
    unit: '%',
    year: 2026,
    data: { kind: 'minimum_tax_rate', scope: 'source_france_income', band: 'upper' },
    ref_ids: ['cgi-197-a'],
    display_order: 3010,
    note: 'Minimum prévu par l’article 197 A.',
    updated_at: null,
  },
  {
    key: 'non-residents-ir-dom-premiere-fraction',
    domain: 'fiscalite-internationale',
    subdomain: 'non-residents-ir',
    label: 'IR non-résidents DOM — première fraction',
    value_numeric: 14.4,
    value_text: null,
    unit: '%',
    year: 2026,
    data: { kind: 'minimum_tax_rate', scope: 'dom_source_income', band: 'first' },
    ref_ids: ['cgi-197-a'],
    display_order: 3020,
    note: 'Minimum prévu par l’article 197 A pour les revenus de source DOM.',
    updated_at: null,
  },
  {
    key: 'non-residents-ir-dom-fraction-superieure',
    domain: 'fiscalite-internationale',
    subdomain: 'non-residents-ir',
    label: 'IR non-résidents DOM — fraction supérieure',
    value_numeric: 20,
    value_text: null,
    unit: '%',
    year: 2026,
    data: { kind: 'minimum_tax_rate', scope: 'dom_source_income', band: 'upper' },
    ref_ids: ['cgi-197-a'],
    display_order: 3030,
    note: 'Minimum prévu par l’article 197 A pour les revenus de source DOM.',
    updated_at: null,
  },
  {
    key: 'non-residents-ifi-assiette-france',
    domain: 'fiscalite-internationale',
    subdomain: 'non-residents-ifi',
    label: 'IFI non-résidents — assiette française',
    value_numeric: null,
    value_text:
      'Actifs immobiliers français et parts à proportion de l’immobilier français taxable',
    unit: null,
    year: 2026,
    data: { kind: 'scope', tax: 'ifi' },
    ref_ids: ['cgi-964'],
    display_order: 3100,
    note: 'Champ d’imposition limité aux actifs français pour les personnes domiciliées hors de France.',
    updated_at: null,
  },
  {
    key: 'non-residents-dmtg-residence-beneficiaire',
    domain: 'fiscalite-internationale',
    subdomain: 'non-residents-transmission',
    label: 'DMTG — bénéficiaire résident fiscal français',
    value_numeric: null,
    value_text:
      'Résidence fiscale française pendant au moins six années au cours des dix années précédentes',
    unit: null,
    year: 2026,
    data: { kind: 'territoriality', tax: 'dmtg' },
    ref_ids: ['cgi-750-ter'],
    display_order: 3200,
    note: 'Critère de territorialité à relire avec les conventions applicables.',
    updated_at: null,
  },
  {
    key: 'non-residents-assurance-vie-residence-beneficiaire',
    domain: 'fiscalite-internationale',
    subdomain: 'non-residents-transmission',
    label: 'Assurance-vie décès — bénéficiaire résident fiscal français',
    value_numeric: null,
    value_text:
      'Résidence fiscale française pendant au moins six années au cours des dix années précédant le décès',
    unit: null,
    year: 2026,
    data: { kind: 'territoriality', tax: 'assurance_vie_deces' },
    ref_ids: ['cgi-990-i'],
    display_order: 3210,
    note: 'Critère d’assujettissement du bénéficiaire à relire avec les conventions applicables.',
    updated_at: null,
  },
  {
    key: 'non-residents-pvi-personne-physique',
    domain: 'fiscalite-internationale',
    subdomain: 'non-residents-immobilier',
    label: 'PVI non-résidents — personne physique',
    value_numeric: 19,
    value_text: null,
    unit: '%',
    year: 2026,
    data: { kind: 'levy_rate', tax: 'pvi', taxpayer: 'individual' },
    ref_ids: ['cgi-244-bis-a'],
    display_order: 3300,
    note: 'Prélèvement sur les plus-values immobilières françaises.',
    updated_at: null,
  },
  {
    key: 'non-residents-pvi-prelevement-solidarite',
    domain: 'fiscalite-internationale',
    subdomain: 'non-residents-immobilier',
    label: 'PVI non-résidents — prélèvement de solidarité',
    value_numeric: 7.5,
    value_text: null,
    unit: '%',
    year: 2026,
    data: { kind: 'solidarity_levy', tax: 'pvi' },
    ref_ids: ['boi-rfpi-pvinr-20-20'],
    display_order: 3310,
    note: 'Cas d’affiliation à un régime étranger de sécurité sociale selon le BOFiP.',
    updated_at: null,
  },
] as const;
