export const MEMENTO_DEMEMBREMENT_REFERENCE_VALUES = [
  {
    key: 'usufruit-viager-moins-21',
    domain: 'demembrement',
    subdomain: 'usufruit-viager',
    label: 'Moins de vingt et un ans révolus',
    value_numeric: null,
    value_text: 'Usufruit 90 % · nue-propriété 10 %',
    unit: null,
    year: 2026,
    data: {
      kind: 'bareme_669_viager',
      maxExclusiveAge: 21,
      usufruitRate: 90,
      bareOwnershipRate: 10,
    },
    ref_ids: ['cgi-669', 'boi-enr-dmtg-10-40-10-50'],
    display_order: 2000,
    note: 'Quote-part de la pleine propriété retenue pour la liquidation fiscale.',
    updated_at: null,
  },
  {
    key: 'usufruit-viager-moins-31',
    domain: 'demembrement',
    subdomain: 'usufruit-viager',
    label: 'Moins de trente et un ans révolus',
    value_numeric: null,
    value_text: 'Usufruit 80 % · nue-propriété 20 %',
    unit: null,
    year: 2026,
    data: {
      kind: 'bareme_669_viager',
      maxExclusiveAge: 31,
      usufruitRate: 80,
      bareOwnershipRate: 20,
    },
    ref_ids: ['cgi-669', 'boi-enr-dmtg-10-40-10-50'],
    display_order: 2010,
    note: 'Quote-part de la pleine propriété retenue pour la liquidation fiscale.',
    updated_at: null,
  },
  {
    key: 'usufruit-viager-moins-41',
    domain: 'demembrement',
    subdomain: 'usufruit-viager',
    label: 'Moins de quarante et un ans révolus',
    value_numeric: null,
    value_text: 'Usufruit 70 % · nue-propriété 30 %',
    unit: null,
    year: 2026,
    data: {
      kind: 'bareme_669_viager',
      maxExclusiveAge: 41,
      usufruitRate: 70,
      bareOwnershipRate: 30,
    },
    ref_ids: ['cgi-669', 'boi-enr-dmtg-10-40-10-50'],
    display_order: 2020,
    note: 'Quote-part de la pleine propriété retenue pour la liquidation fiscale.',
    updated_at: null,
  },
  {
    key: 'usufruit-viager-moins-51',
    domain: 'demembrement',
    subdomain: 'usufruit-viager',
    label: 'Moins de cinquante et un ans révolus',
    value_numeric: null,
    value_text: 'Usufruit 60 % · nue-propriété 40 %',
    unit: null,
    year: 2026,
    data: {
      kind: 'bareme_669_viager',
      maxExclusiveAge: 51,
      usufruitRate: 60,
      bareOwnershipRate: 40,
    },
    ref_ids: ['cgi-669', 'boi-enr-dmtg-10-40-10-50'],
    display_order: 2030,
    note: 'Quote-part de la pleine propriété retenue pour la liquidation fiscale.',
    updated_at: null,
  },
  {
    key: 'usufruit-viager-moins-61',
    domain: 'demembrement',
    subdomain: 'usufruit-viager',
    label: 'Moins de soixante et un ans révolus',
    value_numeric: null,
    value_text: 'Usufruit 50 % · nue-propriété 50 %',
    unit: null,
    year: 2026,
    data: {
      kind: 'bareme_669_viager',
      maxExclusiveAge: 61,
      usufruitRate: 50,
      bareOwnershipRate: 50,
    },
    ref_ids: ['cgi-669', 'boi-enr-dmtg-10-40-10-50'],
    display_order: 2040,
    note: 'Quote-part de la pleine propriété retenue pour la liquidation fiscale.',
    updated_at: null,
  },
  {
    key: 'usufruit-viager-moins-71',
    domain: 'demembrement',
    subdomain: 'usufruit-viager',
    label: 'Moins de soixante et onze ans révolus',
    value_numeric: null,
    value_text: 'Usufruit 40 % · nue-propriété 60 %',
    unit: null,
    year: 2026,
    data: {
      kind: 'bareme_669_viager',
      maxExclusiveAge: 71,
      usufruitRate: 40,
      bareOwnershipRate: 60,
    },
    ref_ids: ['cgi-669', 'boi-enr-dmtg-10-40-10-50'],
    display_order: 2050,
    note: 'Quote-part de la pleine propriété retenue pour la liquidation fiscale.',
    updated_at: null,
  },
  {
    key: 'usufruit-viager-moins-81',
    domain: 'demembrement',
    subdomain: 'usufruit-viager',
    label: 'Moins de quatre-vingt-un ans révolus',
    value_numeric: null,
    value_text: 'Usufruit 30 % · nue-propriété 70 %',
    unit: null,
    year: 2026,
    data: {
      kind: 'bareme_669_viager',
      maxExclusiveAge: 81,
      usufruitRate: 30,
      bareOwnershipRate: 70,
    },
    ref_ids: ['cgi-669', 'boi-enr-dmtg-10-40-10-50'],
    display_order: 2060,
    note: 'Quote-part de la pleine propriété retenue pour la liquidation fiscale.',
    updated_at: null,
  },
  {
    key: 'usufruit-viager-moins-91',
    domain: 'demembrement',
    subdomain: 'usufruit-viager',
    label: 'Moins de quatre-vingt-onze ans révolus',
    value_numeric: null,
    value_text: 'Usufruit 20 % · nue-propriété 80 %',
    unit: null,
    year: 2026,
    data: {
      kind: 'bareme_669_viager',
      maxExclusiveAge: 91,
      usufruitRate: 20,
      bareOwnershipRate: 80,
    },
    ref_ids: ['cgi-669', 'boi-enr-dmtg-10-40-10-50'],
    display_order: 2070,
    note: 'Quote-part de la pleine propriété retenue pour la liquidation fiscale.',
    updated_at: null,
  },
  {
    key: 'usufruit-viager-plus-91',
    domain: 'demembrement',
    subdomain: 'usufruit-viager',
    label: 'Plus de quatre-vingt-dix ans révolus',
    value_numeric: null,
    value_text: 'Usufruit 10 % · nue-propriété 90 %',
    unit: null,
    year: 2026,
    data: { kind: 'bareme_669_viager', minAge: 91, usufruitRate: 10, bareOwnershipRate: 90 },
    ref_ids: ['cgi-669', 'boi-enr-dmtg-10-40-10-50'],
    display_order: 2080,
    note: 'Quote-part de la pleine propriété retenue pour la liquidation fiscale.',
    updated_at: null,
  },
  {
    key: 'usufruit-temporaire-periode',
    domain: 'demembrement',
    subdomain: 'usufruit-temporaire',
    label: 'Usufruit temporaire — période de dix ans',
    value_numeric: 23,
    value_text: null,
    unit: '%',
    year: 2026,
    data: { kind: 'bareme_669_temporaire', periodYears: 10 },
    ref_ids: ['cgi-669', 'boi-enr-dmtg-10-40-10-50'],
    display_order: 2090,
    note: 'Période retenue sans fraction et sans égard à l’âge de l’usufruitier.',
    updated_at: null,
  },
] as const;
