import type { RoadmapOnlySimulatorId, SimulatorCoverageEntry } from './simulatorCoverage';

export const ROADMAP_ONLY_SIMULATOR_IDS = [
  'obo',
  'fiscalite-societe',
  'prevoyance-dirigeant',
  'donation-demembrement-societe',
  'succession-liquidite-societe',
] as const satisfies readonly RoadmapOnlySimulatorId[];

export const SIMULATOR_MEMENTO_COVERAGE = [
  {
    target: { kind: 'registry', simulatorId: 'filiation' },
    chapterId: 'foyer',
    sectionLabel: 'Filiation familiale',
    expectedStatus: 'planned',
  },
  {
    target: { kind: 'registry', simulatorId: 'regime-matrimonial' },
    chapterId: 'civil',
    sectionLabel: 'Régime matrimonial',
    expectedStatus: 'planned',
  },
  {
    target: { kind: 'registry', simulatorId: 'donations-anterieures' },
    chapterId: 'transmission',
    sectionLabel: 'Donations antérieures',
    expectedStatus: 'planned',
  },
  {
    target: { kind: 'registry', simulatorId: 'actif-passif' },
    chapterId: 'patrimoine',
    sectionLabel: 'Synthèse actif-passif',
    expectedStatus: 'a_verifier',
    note: 'Lifecycle internalOnly lu dans la registry ; le mémento ne l’expose pas comme statut.',
  },
  {
    target: { kind: 'registry', simulatorId: 'budget' },
    chapterId: 'foyer',
    sectionLabel: 'Budget',
    expectedStatus: 'planned',
  },
  {
    target: { kind: 'registry', simulatorId: 'ir' },
    chapterId: 'fiscalite-foyer',
    sectionLabel: 'IR',
    expectedStatus: 'couvert',
  },
  {
    target: { kind: 'registry', simulatorId: 'ifi' },
    chapterId: 'fiscalite-foyer',
    sectionLabel: 'IFI',
    expectedStatus: 'planned',
  },
  {
    target: { kind: 'registry', simulatorId: 'retraite' },
    chapterId: 'retraite',
    sectionLabel: 'Retraite globale',
    expectedStatus: 'planned',
  },
  {
    target: { kind: 'registry', simulatorId: 'per' },
    chapterId: 'epargne-retraite',
    sectionLabel: 'PER',
    expectedStatus: 'couvert',
  },
  {
    target: { kind: 'registry', simulatorId: 'per-potentiel' },
    chapterId: 'epargne-retraite',
    sectionLabel: 'Potentiel PER',
    expectedStatus: 'couvert',
  },
  {
    target: { kind: 'registry', simulatorId: 'per-transfert' },
    chapterId: 'epargne-retraite',
    sectionLabel: 'Transfert PER',
    expectedStatus: 'couvert',
  },
  {
    target: { kind: 'registry', simulatorId: 'placement' },
    chapterId: 'placements',
    sectionLabel: 'Allocation',
    expectedStatus: 'couvert',
  },
  {
    target: {
      kind: 'subtype',
      parentSimulatorId: 'placement',
      subtypeLabel: 'Assurance-vie / capitalisation',
    },
    chapterId: 'placements',
    sectionLabel: 'Assurance-vie et capitalisation',
    expectedStatus: 'partiel',
  },
  {
    target: { kind: 'subtype', parentSimulatorId: 'placement', subtypeLabel: 'PEA' },
    chapterId: 'placements',
    sectionLabel: 'PEA',
    expectedStatus: 'partiel',
  },
  {
    target: { kind: 'subtype', parentSimulatorId: 'placement', subtypeLabel: 'CTO' },
    chapterId: 'placements',
    sectionLabel: 'CTO',
    expectedStatus: 'partiel',
  },
  {
    target: { kind: 'registry', simulatorId: 'credit' },
    chapterId: 'immobilier',
    sectionLabel: 'Crédit',
    expectedStatus: 'couvert',
  },
  {
    target: { kind: 'registry', simulatorId: 'investissement-locatif' },
    chapterId: 'immobilier',
    sectionLabel: 'Investissement locatif',
    expectedStatus: 'planned',
  },
  {
    target: { kind: 'registry', simulatorId: 'revenus-fonciers' },
    chapterId: 'immobilier',
    sectionLabel: 'Revenus fonciers',
    expectedStatus: 'planned',
  },
  {
    target: { kind: 'registry', simulatorId: 'lmnp-lmp' },
    chapterId: 'immobilier',
    sectionLabel: 'Location meublée',
    expectedStatus: 'planned',
  },
  {
    target: { kind: 'registry', simulatorId: 'scpi' },
    chapterId: 'immobilier',
    sectionLabel: 'SCPI',
    expectedStatus: 'planned',
  },
  {
    target: { kind: 'registry', simulatorId: 'sci' },
    chapterId: 'immobilier',
    sectionLabel: 'SCI',
    expectedStatus: 'planned',
  },
  {
    target: { kind: 'registry', simulatorId: 'plus-values-immobilieres' },
    chapterId: 'immobilier',
    sectionLabel: 'PV immobilières',
    expectedStatus: 'planned',
  },
  {
    target: { kind: 'registry', simulatorId: 'arbitrage-reemploi' },
    chapterId: 'arbitrage',
    sectionLabel: 'Réemploi',
    expectedStatus: 'planned',
  },
  {
    target: { kind: 'registry', simulatorId: 'prevoyance' },
    chapterId: 'prevoyance',
    sectionLabel: 'Protection familiale',
    expectedStatus: 'partiel',
  },
  {
    target: { kind: 'registry', simulatorId: 'succession' },
    chapterId: 'transmission',
    sectionLabel: 'Succession',
    expectedStatus: 'couvert',
  },
  {
    target: { kind: 'registry', simulatorId: 'donation-demembrement' },
    chapterId: 'transmission',
    sectionLabel: 'Donation',
    expectedStatus: 'planned',
  },
  {
    target: { kind: 'registry', simulatorId: 'organigramme-societe' },
    chapterId: 'societe',
    sectionLabel: 'Organigramme',
    expectedStatus: 'planned',
  },
  {
    target: { kind: 'registry', simulatorId: 'valorisation-titres' },
    chapterId: 'societe',
    sectionLabel: 'Valorisation',
    expectedStatus: 'planned',
  },
  {
    target: { kind: 'registry', simulatorId: 'projection-comptable' },
    chapterId: 'societe',
    sectionLabel: 'Projection comptable',
    expectedStatus: 'planned',
  },
  {
    target: { kind: 'registry', simulatorId: 'tresorerie-societe' },
    chapterId: 'societe',
    sectionLabel: 'Trésorerie',
    expectedStatus: 'partiel',
  },
  {
    target: {
      kind: 'subtype',
      parentSimulatorId: 'tresorerie-societe',
      subtypeLabel: 'Placement trésorerie intégré',
    },
    chapterId: 'societe',
    sectionLabel: 'Placement trésorerie',
    expectedStatus: 'partiel',
  },
  {
    target: { kind: 'subtype', parentSimulatorId: 'tresorerie-societe', subtypeLabel: 'CCA' },
    chapterId: 'societe',
    sectionLabel: 'CCA',
    expectedStatus: 'planned',
  },
  {
    target: { kind: 'subtype', parentSimulatorId: 'tresorerie-societe', subtypeLabel: 'Filiales' },
    chapterId: 'societe',
    sectionLabel: 'Groupe',
    expectedStatus: 'planned',
  },
  {
    target: {
      kind: 'subtype',
      parentSimulatorId: 'tresorerie-societe',
      subtypeLabel: 'Emprunts société',
    },
    chapterId: 'societe',
    sectionLabel: 'Financement',
    expectedStatus: 'planned',
  },
  {
    target: { kind: 'registry', simulatorId: 'remuneration' },
    chapterId: 'dirigeant',
    sectionLabel: 'Rémunération',
    expectedStatus: 'planned',
  },
  {
    target: { kind: 'registry', simulatorId: 'epargne-salariale' },
    chapterId: 'societe',
    sectionLabel: 'Épargne salariale',
    expectedStatus: 'planned',
    note: 'Lifecycle placeholder lu dans la registry ; le mémento garde un statut planned.',
  },
  {
    target: { kind: 'registry', simulatorId: 'cession-titres' },
    chapterId: 'societe',
    sectionLabel: 'Cession',
    expectedStatus: 'planned',
  },
  {
    target: { kind: 'registry', simulatorId: 'sortie-capitaux' },
    chapterId: 'dirigeant',
    sectionLabel: 'Sortie de capitaux',
    expectedStatus: 'planned',
  },
  {
    target: { kind: 'registry', simulatorId: 'holding' },
    chapterId: 'societe',
    sectionLabel: 'Holding',
    expectedStatus: 'planned',
  },
  {
    target: { kind: 'registry', simulatorId: 'pacte-dutreil' },
    chapterId: 'transmission-entreprise',
    sectionLabel: 'Dutreil',
    expectedStatus: 'planned',
  },
  {
    target: { kind: 'roadmap-only', roadmapId: 'obo', roadmapLabel: 'OBO' },
    chapterId: 'societe',
    sectionLabel: 'OBO',
    expectedStatus: 'a_verifier',
  },
  {
    target: {
      kind: 'roadmap-only',
      roadmapId: 'fiscalite-societe',
      roadmapLabel: 'Fiscalité société',
    },
    chapterId: 'societe',
    sectionLabel: 'Fiscalité société',
    expectedStatus: 'a_verifier',
    note: 'ROADMAP-only internalOnly : il reste séparé du lifecycle registry.',
  },
  {
    target: {
      kind: 'roadmap-only',
      roadmapId: 'prevoyance-dirigeant',
      roadmapLabel: 'Prévoyance dirigeant',
    },
    chapterId: 'dirigeant',
    sectionLabel: 'Prévoyance',
    expectedStatus: 'planned',
  },
  {
    target: {
      kind: 'roadmap-only',
      roadmapId: 'donation-demembrement-societe',
      roadmapLabel: 'Donation & démembrement société',
    },
    chapterId: 'transmission-entreprise',
    sectionLabel: 'Donation titres',
    expectedStatus: 'planned',
  },
  {
    target: {
      kind: 'roadmap-only',
      roadmapId: 'succession-liquidite-societe',
      roadmapLabel: 'Succession & liquidité société',
    },
    chapterId: 'transmission-entreprise',
    sectionLabel: 'Liquidité',
    expectedStatus: 'planned',
  },
] as const satisfies readonly SimulatorCoverageEntry[];
