import { standalone } from '../contextPolicies';
import type { SimulatorDefinition } from '../types';

export const FOYER_PILOTER_SIMULATORS = [
  {
    id: 'retraite',
    space: 'foyer',
    tab: 'piloter',
    family: 'Retraite & effort d’épargne',
    shortLabel: 'Retraite globale',
    fullLabel: 'Retraite globale',
    objective: 'Projeter le besoin retraite global avant allocation vers PER ou placements.',
    inputs: ['âge', 'revenus', 'droits estimés', 'budget cible', 'effort d’épargne'],
    calculates: ['besoin annuel', 'écart de revenus', 'effort cible', 'horizon de financement'],
    outputs: ['besoin retraite', 'effort cible', 'priorités de financement'],
    upstream: ['budget', 'ir'],
    next: ['per', 'placement', 'succession'],
    dossierFields: ['retraite', 'budget', 'fiscaliteIR'],
    legalRefs: [],
    legalRefsStatus: 'a-renseigner-avant-codage',
    testScenarios: ['salarié proche retraite', 'TNS', 'couple avec écart de droits'],
    contextPolicy: standalone(
      ['age', 'revenus', 'budget'],
      ['retraite', 'budget'],
      ['fiscaliteIR'],
    ),
    lifecycle: 'planned',
    visibility: 'simplifie',
  },
  {
    id: 'per',
    routeId: 'per',
    space: 'foyer',
    tab: 'piloter',
    family: 'Retraite & effort d’épargne',
    shortLabel: 'PER',
    fullLabel: 'PER / épargne retraite',
    objective: 'Orienter vers le potentiel de versement PER ou le transfert de contrats retraite.',
    inputs: ['revenus', 'plafonds retraite', 'contrats existants', 'horizon', 'TMI'],
    calculates: ['orientation PER', 'leviers disponibles', 'points de contrôle transfert'],
    outputs: ['parcours PER recommandé', 'hypothèses à compléter', 'simulateurs PER aval'],
    upstream: ['budget', 'ir', 'retraite'],
    next: ['per-potentiel', 'per-transfert', 'placement', 'succession'],
    dossierFields: ['retraite', 'fiscaliteIR', 'placements'],
    legalRefs: ['CGI art. 154 bis', 'CGI art. 163 quatervicies', 'CMF art. L224-1 et suivants'],
    legalRefsStatus: 'complete',
    testScenarios: ['orientation potentiel', 'orientation transfert', 'dossier incomplet'],
    contextPolicy: standalone(['revenus', 'horizon'], ['retraite', 'fiscaliteIR'], ['placements']),
    subtypes: ['PER individuel', 'PER assurance', 'PER bancaire', 'Contrat retraite transférable'],
    lifecycle: 'hub',
    visibility: 'simplifie',
  },
  {
    id: 'per-potentiel',
    routeId: 'per-potentiel',
    space: 'foyer',
    tab: 'piloter',
    family: 'Retraite & effort d’épargne',
    shortLabel: 'Potentiel PER',
    fullLabel: 'PER — Potentiel',
    objective: 'Calculer l’intérêt fiscal et patrimonial de versements PER.',
    inputs: ['revenus', 'plafonds', 'versements', 'TMI', 'horizon'],
    calculates: ['économie IR', 'effort net', 'plafonds utilisés', 'impact à la sortie'],
    outputs: ['versement recommandé', 'économie fiscale', 'effort net', 'plafonds restants'],
    upstream: ['per', 'ir', 'budget'],
    next: ['placement', 'succession'],
    dossierFields: ['retraite.plafonds', 'fiscaliteIR', 'budget'],
    legalRefs: ['CGI art. 154 bis', 'CGI art. 163 quatervicies'],
    legalRefsStatus: 'complete',
    testScenarios: ['salarié avec plafond disponible', 'TNS Madelin', 'plafond saturé'],
    contextPolicy: standalone(['revenus', 'versement'], ['fiscaliteIR'], ['retraite.plafonds']),
    lifecycle: 'active',
    visibility: 'simplifie',
    engine: 'src/engine/per',
  },
  {
    id: 'per-transfert',
    routeId: 'per-transfert',
    space: 'foyer',
    tab: 'piloter',
    family: 'Retraite & effort d’épargne',
    shortLabel: 'Transfert PER',
    fullLabel: 'PER — Transfert',
    objective: 'Comparer le maintien d’un contrat retraite et son transfert vers un nouveau PER.',
    inputs: ['contrat actuel', 'nouveau contrat', 'frais', 'rendements', 'rente', 'horizon'],
    calculates: ['capital projeté', 'rente projetée', 'écart de frais', 'points contractuels'],
    outputs: ['comparaison transfert', 'écart de capital', 'écart de rente', 'alertes contrat'],
    upstream: ['per', 'retraite'],
    next: ['placement', 'succession'],
    dossierFields: ['retraite.contrats', 'placements', 'fiscaliteIR'],
    legalRefs: ['CMF art. L224-40', 'CMF art. L224-1 et suivants'],
    legalRefsStatus: 'complete',
    testScenarios: ['transfert favorable', 'maintien favorable', 'données assureur incomplètes'],
    contextPolicy: standalone(
      ['contratActuel', 'nouveauContrat'],
      ['retraite.contrats'],
      ['fiscaliteIR'],
    ),
    lifecycle: 'active',
    visibility: 'expert',
    engine: 'src/engine/per/transfert',
  },
  {
    id: 'placement',
    routeId: 'placement',
    space: 'foyer',
    tab: 'piloter',
    family: 'Placements financiers',
    shortLabel: 'Placement & allocation',
    fullLabel: 'Placement & allocation patrimoniale',
    objective:
      'Comparer des enveloppes et allocations en accumulation, liquidation et transmission.',
    inputs: ['capital', 'versements', 'horizon', 'enveloppes', 'fiscalité', 'transmission'],
    calculates: [
      'capital net',
      'revenus nets',
      'fiscalité',
      'transmission',
      'comparaison enveloppes',
    ],
    outputs: ['comparaison nette', 'allocation cible', 'capital projeté', 'fiscalité estimée'],
    upstream: ['budget', 'ir', 'retraite'],
    next: ['succession', 'arbitrage-reemploi', 'per'],
    dossierFields: ['placements', 'budget', 'fiscaliteIR', 'succession'],
    legalRefs: ['CGI art. 125-0 A', 'CGI art. 150-0 A', 'CGI art. 200 A', 'CGI art. 990 I'],
    legalRefsStatus: 'complete',
    testScenarios: ['assurance-vie vs CTO', 'PEA/CTO en sous-type', 'liquidation avec fiscalité'],
    contextPolicy: standalone(['capital', 'horizon'], ['placements', 'fiscaliteIR'], ['budget']),
    subtypes: [
      'Assurance-vie / capitalisation',
      'Contrat de capitalisation',
      'PEA',
      'CTO',
      'SCPI',
      'Comparaison de deux enveloppes',
    ],
    lifecycle: 'active',
    visibility: 'simplifie',
    engine: 'src/engine/placement',
  },
  {
    id: 'credit',
    routeId: 'credit',
    space: 'foyer',
    tab: 'piloter',
    family: 'Immobilier',
    shortLabel: 'Crédit & garanties',
    fullLabel: 'Crédit & garanties',
    objective: 'Simuler les échéanciers, garanties et effets de lissage de crédits patrimoniaux.',
    inputs: ['capital', 'taux', 'durée', 'assurance', 'paliers', 'prêts complémentaires'],
    calculates: ['échéancier', 'coût du crédit', 'assurance', 'lissage', 'charge mensuelle'],
    outputs: ['échéancier', 'coût total', 'charge mensuelle', 'synthèse assurance'],
    upstream: ['budget'],
    next: ['investissement-locatif', 'prevoyance', 'placement'],
    dossierFields: ['credits', 'budget', 'immobilier'],
    legalRefs: [
      'Code de la consommation art. L313-1 et suivants',
      'Code des assurances art. L113-2',
    ],
    legalRefsStatus: 'complete',
    testScenarios: ['prêt simple', 'trois prêts lissés', 'assurance emprunteur'],
    contextPolicy: standalone(
      ['credit.capital', 'credit.taux', 'credit.duree'],
      ['budget'],
      ['credits'],
    ),
    lifecycle: 'active',
    visibility: 'simplifie',
    engine: 'src/engine/credit',
  },
  {
    id: 'investissement-locatif',
    space: 'foyer',
    tab: 'piloter',
    family: 'Immobilier',
    shortLabel: 'Invest. locatif',
    fullLabel: 'Investissement locatif',
    objective: 'Évaluer la viabilité patrimoniale et fiscale d’un projet locatif.',
    inputs: ['prix', 'frais', 'loyers', 'charges', 'crédit', 'régime fiscal', 'horizon'],
    calculates: [
      'rendement brut/net',
      'cash-flow',
      'effort d’épargne',
      'fiscalité',
      'impact crédit',
    ],
    outputs: ['cash-flow annuel', 'rentabilité nette', 'effort mensuel', 'fiscalité projetée'],
    upstream: ['budget', 'credit', 'ir'],
    next: ['revenus-fonciers', 'lmnp-lmp', 'ifi', 'plus-values-immobilieres'],
    dossierFields: ['budget', 'fiscaliteIR', 'credits', 'immobilier'],
    legalRefs: [],
    legalRefsStatus: 'a-renseigner-avant-codage',
    testScenarios: ['projet avec crédit', 'cash-flow négatif', 'projet sans crédit'],
    contextPolicy: standalone(
      ['budget.capaciteEpargne', 'immobilier.prix'],
      ['budget'],
      ['credits'],
    ),
    lifecycle: 'planned',
    visibility: 'simplifie',
  },
  {
    id: 'revenus-fonciers',
    space: 'foyer',
    tab: 'piloter',
    family: 'Immobilier',
    shortLabel: 'Revenus fonciers',
    fullLabel: 'Revenus fonciers',
    objective: 'Qualifier la fiscalité des revenus fonciers existants ou projetés.',
    inputs: ['loyers', 'charges', 'intérêts', 'travaux', 'régime fiscal'],
    calculates: [
      'résultat foncier',
      'déficit éventuel',
      'impact IR',
      'impact prélèvements sociaux',
    ],
    outputs: ['résultat foncier', 'déficit reportable', 'impact fiscal'],
    upstream: ['investissement-locatif', 'ir'],
    next: ['ifi', 'plus-values-immobilieres', 'arbitrage-reemploi'],
    dossierFields: ['immobilier.revenus', 'fiscaliteIR'],
    legalRefs: [],
    legalRefsStatus: 'a-renseigner-avant-codage',
    testScenarios: ['micro-foncier', 'réel avec déficit', 'travaux importants'],
    contextPolicy: standalone(['loyers', 'charges'], ['immobilier'], ['fiscaliteIR']),
    lifecycle: 'planned',
    visibility: 'simplifie',
  },
  {
    id: 'lmnp-lmp',
    space: 'foyer',
    tab: 'piloter',
    family: 'Immobilier',
    shortLabel: 'LMNP / LMP',
    fullLabel: 'LMNP / LMP',
    objective: 'Comparer les effets patrimoniaux et fiscaux de la location meublée.',
    inputs: ['loyers meublés', 'charges', 'amortissements', 'statut', 'horizon'],
    calculates: ['résultat fiscal', 'amortissements', 'statut LMNP/LMP', 'cash-flow'],
    outputs: ['résultat meublé', 'stock amortissements', 'alerte statut'],
    upstream: ['investissement-locatif', 'ir'],
    next: ['plus-values-immobilieres', 'arbitrage-reemploi'],
    dossierFields: ['immobilier.meuble', 'fiscaliteIR'],
    legalRefs: [],
    legalRefsStatus: 'a-renseigner-avant-codage',
    testScenarios: ['LMNP au réel', 'bascule LMP', 'déficit comptable'],
    contextPolicy: standalone(['loyers', 'charges'], ['immobilier'], ['fiscaliteIR']),
    lifecycle: 'planned',
    visibility: 'expert',
  },
  {
    id: 'scpi',
    space: 'foyer',
    tab: 'piloter',
    family: 'Immobilier',
    shortLabel: 'SCPI',
    fullLabel: 'SCPI',
    objective: 'Analyser une allocation SCPI dans le patrimoine financier et immobilier.',
    inputs: ['capital', 'rendement', 'frais', 'crédit', 'horizon'],
    calculates: ['revenu net', 'fiscalité', 'liquidité', 'impact crédit'],
    outputs: ['revenu projeté', 'fiscalité estimée', 'risques de liquidité'],
    upstream: ['placement', 'credit'],
    next: ['ifi', 'succession'],
    dossierFields: ['placements', 'immobilier', 'fiscaliteIR'],
    legalRefs: [],
    legalRefsStatus: 'a-renseigner-avant-codage',
    testScenarios: ['SCPI comptant', 'SCPI à crédit', 'SCPI en assurance-vie'],
    contextPolicy: standalone(['capital', 'rendement'], ['placements'], ['fiscaliteIR']),
    lifecycle: 'planned',
    visibility: 'expert',
  },
  {
    id: 'sci',
    space: 'foyer',
    tab: 'piloter',
    family: 'Immobilier',
    shortLabel: 'SCI',
    fullLabel: 'SCI & mode de détention',
    objective: 'Comparer le mode de détention immobilier et ses effets civils ou fiscaux.',
    inputs: ['immeuble', 'associés', 'statuts', 'financement', 'objectif'],
    calculates: ['mode de détention', 'flux associés', 'points civils', 'transmission possible'],
    outputs: ['structure de détention', 'alertes statuts', 'étapes aval'],
    upstream: ['actif-passif', 'investissement-locatif'],
    next: ['donation-demembrement', 'plus-values-immobilieres'],
    dossierFields: ['immobilier', 'famille', 'societes'],
    legalRefs: [],
    legalRefsStatus: 'a-renseigner-avant-codage',
    testScenarios: ['SCI familiale', 'SCI à l’IS', 'détention en indivision'],
    contextPolicy: standalone(['immobilier', 'associés'], ['immobilier'], ['famille']),
    lifecycle: 'planned',
    visibility: 'expert',
  },
  {
    id: 'plus-values-immobilieres',
    space: 'foyer',
    tab: 'piloter',
    family: 'Arbitrer',
    shortLabel: 'Plus-values immo.',
    fullLabel: 'Plus-values immobilières',
    objective: 'Estimer l’impact fiscal d’une cession immobilière.',
    inputs: ['prix acquisition', 'prix cession', 'durée de détention', 'travaux', 'frais'],
    calculates: ['plus-value brute', 'abattements', 'impôt', 'prélèvements sociaux'],
    outputs: ['plus-value nette', 'fiscalité de cession', 'cash net'],
    upstream: ['investissement-locatif', 'revenus-fonciers', 'ifi'],
    next: ['arbitrage-reemploi', 'placement'],
    dossierFields: ['immobilier', 'fiscaliteIR'],
    legalRefs: [],
    legalRefsStatus: 'a-renseigner-avant-codage',
    testScenarios: ['résidence secondaire', 'longue détention', 'travaux forfaitaires'],
    contextPolicy: standalone(['prixAcquisition', 'prixCession'], ['immobilier'], ['fiscaliteIR']),
    lifecycle: 'planned',
    visibility: 'simplifie',
  },
  {
    id: 'arbitrage-reemploi',
    space: 'foyer',
    tab: 'piloter',
    family: 'Arbitrer',
    shortLabel: 'Vendre / réemployer',
    fullLabel: 'Vendre / conserver / réemployer',
    objective: 'Comparer la conservation d’un actif et son réemploi patrimonial.',
    inputs: ['actif', 'valeur', 'fiscalité de sortie', 'supports de réemploi', 'horizon'],
    calculates: ['cash net', 'rendement comparé', 'risque', 'liquidité', 'impact succession'],
    outputs: ['arbitrage recommandé', 'cash réemployable', 'allocation de réemploi'],
    upstream: ['plus-values-immobilieres', 'cession-titres', 'placement'],
    next: ['placement', 'retraite', 'succession'],
    dossierFields: ['patrimoine', 'placements', 'fiscaliteIR'],
    legalRefs: [],
    legalRefsStatus: 'a-renseigner-avant-codage',
    testScenarios: ['cession immobilière', 'cession de titres', 'réemploi assurance-vie'],
    contextPolicy: standalone(['actif', 'valeur'], ['patrimoine'], ['fiscaliteIR']),
    lifecycle: 'planned',
    visibility: 'simplifie',
  },
] as const satisfies readonly SimulatorDefinition[];
