import { dossierFirst, standalone } from '../contextPolicies';
import type { SimulatorDefinition } from '../types';

export const FOYER_COMPRENDRE_SIMULATORS = [
  {
    id: 'filiation',
    space: 'foyer',
    tab: 'comprendre',
    family: 'Foyer',
    shortLabel: 'Filiation',
    fullLabel: 'Filiation familiale',
    objective: 'Structurer les personnes du foyer, leurs liens et les branches familiales utiles.',
    inputs: ['déclarants', 'conjoint', 'enfants', 'personnes à charge', 'liens familiaux'],
    calculates: [
      'structure familiale exploitable',
      'branches de transmission',
      'personnes à protéger',
    ],
    outputs: ['foyer normalisé', 'liste des membres', 'liens de parenté', 'branches familiales'],
    upstream: [],
    next: ['regime-matrimonial', 'budget', 'prevoyance', 'succession'],
    dossierFields: ['foyer', 'famille'],
    legalRefs: [],
    legalRefsStatus: 'a-renseigner-avant-codage',
    testScenarios: ['couple avec enfants', 'famille recomposée', 'personne seule sans descendant'],
    contextPolicy: standalone(['foyer.membres'], ['foyer'], ['famille']),
    lifecycle: 'planned',
    visibility: 'simplifie',
  },
  {
    id: 'regime-matrimonial',
    space: 'foyer',
    tab: 'comprendre',
    family: 'Foyer',
    shortLabel: 'Régime matrimonial',
    fullLabel: 'Régime matrimonial & protection conjoint',
    objective: 'Qualifier le régime du couple et ses effets patrimoniaux avant transmission.',
    inputs: ['statut conjugal', 'régime', 'contrat', 'clauses', 'date'],
    calculates: [
      'qualification civile',
      'effets sur masses patrimoniales',
      'points de vigilance conjoint',
    ],
    outputs: ['régime qualifié', 'clauses utiles', 'masses à reprendre par les simulateurs'],
    upstream: ['filiation'],
    next: ['donations-anterieures', 'succession', 'prevoyance'],
    dossierFields: ['foyer.regimeMatrimonial'],
    legalRefs: [],
    legalRefsStatus: 'a-renseigner-avant-codage',
    testScenarios: ['communauté réduite aux acquêts', 'séparation de biens', 'PACS avec testament'],
    contextPolicy: standalone(['foyer.statutConjugal'], ['foyer'], ['famille']),
    lifecycle: 'planned',
    visibility: 'simplifie',
  },
  {
    id: 'donations-anterieures',
    space: 'foyer',
    tab: 'comprendre',
    family: 'Transmission',
    shortLabel: 'Donations antérieures',
    fullLabel: 'Donations antérieures',
    objective:
      'Recenser les donations déjà consenties et leurs effets sur les abattements disponibles.',
    inputs: ['donateurs', 'bénéficiaires', 'dates', 'valeurs', 'nature des donations'],
    calculates: ['rappel fiscal à qualifier', 'abattements consommés', 'donations à réintégrer'],
    outputs: ['historique donations', 'abattements consommés', 'points de contrôle'],
    upstream: ['filiation', 'regime-matrimonial'],
    next: ['succession', 'donation-demembrement'],
    dossierFields: ['donations', 'famille'],
    legalRefs: [],
    legalRefsStatus: 'a-renseigner-avant-codage',
    testScenarios: ['donation simple', 'donation-partage', 'donation en démembrement'],
    contextPolicy: standalone(['donations'], ['donations'], ['famille']),
    lifecycle: 'planned',
    visibility: 'simplifie',
  },
  {
    id: 'actif-passif',
    space: 'foyer',
    tab: 'comprendre',
    family: 'Patrimoine',
    shortLabel: 'Actif / passif',
    fullLabel: 'Actif / passif interne',
    objective: 'Normaliser le patrimoine net du dossier pour alimenter les analyses aval.',
    inputs: ['actifs', 'passifs', 'détenteurs', 'liquidité', 'valeurs'],
    calculates: ['patrimoine brut', 'patrimoine net', 'répartition par poche', 'liquidité'],
    outputs: ['patrimoine net', 'poche immobilière', 'poche financière', 'dettes'],
    upstream: ['filiation', 'regime-matrimonial'],
    next: ['ifi', 'succession', 'placement'],
    dossierFields: ['patrimoine.actifs', 'patrimoine.passifs'],
    legalRefs: [],
    legalRefsStatus: 'a-renseigner-avant-codage',
    testScenarios: ['patrimoine immobilier dominant', 'passif significatif', 'patrimoine liquide'],
    contextPolicy: dossierFirst(['patrimoine'], ['foyer']),
    lifecycle: 'internalOnly',
    visibility: 'internal',
  },
  {
    id: 'budget',
    space: 'foyer',
    tab: 'comprendre',
    family: 'Foyer',
    shortLabel: 'Budget & épargne',
    fullLabel: 'Budget & capacité d’épargne',
    objective: 'Mesurer la capacité d’épargne et la soutenabilité des stratégies proposées.',
    inputs: ['revenus', 'charges', 'épargne actuelle', 'effort cible', 'horizon'],
    calculates: ['capacité d’épargne', 'reste à vivre', 'effort disponible', 'marge de sécurité'],
    outputs: [
      'budget normalisé',
      'capacité mensuelle',
      'effort annuel',
      'alertes de soutenabilité',
    ],
    upstream: ['filiation'],
    next: ['ir', 'credit', 'retraite', 'placement'],
    dossierFields: ['budget', 'revenus', 'charges'],
    legalRefs: [],
    legalRefsStatus: 'a-renseigner-avant-codage',
    testScenarios: ['capacité positive', 'effort contraint', 'revenus irréguliers'],
    contextPolicy: standalone(['budget.revenus', 'budget.charges'], ['budget'], ['fiscaliteIR']),
    lifecycle: 'planned',
    visibility: 'simplifie',
  },
  {
    id: 'ir',
    routeId: 'ir',
    space: 'foyer',
    tab: 'comprendre',
    family: 'Fiscalité',
    shortLabel: 'Fiscalité IR',
    fullLabel: 'Impôt sur le revenu',
    objective: 'Estimer l’impôt, la TMI et les effets de revenus ou charges du foyer.',
    inputs: ['situation familiale', 'revenus', 'charges', 'crédits', 'option capital'],
    calculates: ['impôt estimé', 'TMI', 'CEHR', 'effet des charges', 'option PFU/barème'],
    outputs: ['impôt estimé', 'TMI', 'CEHR', 'revenu imposable', 'ventilation des revenus'],
    upstream: ['filiation', 'budget'],
    next: ['placement', 'per', 'credit', 'retraite'],
    dossierFields: ['foyer', 'revenus', 'fiscaliteIR'],
    legalRefs: ['cgi-193-197', 'cgi-200-a', 'cgi-223-sexies'],
    legalRefsStatus: 'complete',
    testScenarios: ['foyer salarié', 'revenus du capital avec PFU', 'CEHR applicable'],
    contextPolicy: standalone(['foyer', 'revenus'], ['foyer', 'revenus'], ['charges', 'capital']),
    lifecycle: 'active',
    visibility: 'simplifie',
    engine: 'src/engine/ir',
  },
  {
    id: 'ifi',
    space: 'foyer',
    tab: 'comprendre',
    family: 'Fiscalité',
    shortLabel: 'IFI',
    fullLabel: 'IFI',
    objective: 'Qualifier l’exposition IFI du patrimoine immobilier net.',
    inputs: ['actifs immobiliers', 'dettes déductibles', 'détention', 'résidence principale'],
    calculates: ['base IFI', 'actifs imposables', 'passifs retenus', 'seuils à contrôler'],
    outputs: ['base taxable IFI', 'alerte seuil', 'liste des actifs à documenter'],
    upstream: ['actif-passif'],
    next: ['donation-demembrement', 'arbitrage-reemploi'],
    dossierFields: ['patrimoine.immobilier', 'passifs', 'ifi'],
    legalRefs: [],
    legalRefsStatus: 'a-renseigner-avant-codage',
    testScenarios: ['patrimoine sous seuil', 'résidence principale', 'dettes immobilières'],
    contextPolicy: dossierFirst(['patrimoine.immobilier'], ['passifs']),
    lifecycle: 'planned',
    visibility: 'expert',
  },
] as const satisfies readonly SimulatorDefinition[];
