import { standalone } from '../contextPolicies';
import type { SimulatorDefinition } from '../types';

export const FOYER_PROTEGER_SIMULATORS = [
  {
    id: 'prevoyance',
    routeId: 'prevoyance',
    space: 'foyer',
    tab: 'proteger',
    family: 'Protection',
    shortLabel: 'Prévoyance',
    fullLabel: 'Prévoyance',
    objective: 'Évaluer les garanties décès, arrêt de travail et protection familiale.',
    inputs: ['situation', 'régime obligatoire', 'contrats', 'revenus', 'bénéficiaires'],
    calculates: ['couverture décès', 'couverture arrêt', 'reste à charge', 'besoin de protection'],
    outputs: ['synthèse garanties', 'besoin non couvert', 'capitaux par bénéficiaire'],
    upstream: ['filiation', 'budget', 'credit'],
    next: ['succession', 'placement'],
    dossierFields: ['foyer', 'prevoyance', 'budget'],
    legalRefs: ['Code de la sécurité sociale art. L911-1', 'Code des assurances art. L132-1'],
    legalRefsStatus: 'complete',
    testScenarios: ['salarié couvert', 'TNS peu couvert', 'besoin capital décès'],
    contextPolicy: standalone(['situation', 'revenus'], ['foyer', 'budget'], ['contrats']),
    lifecycle: 'active',
    visibility: 'simplifie',
    engine: 'src/domain/prevoyance',
  },
  {
    id: 'succession',
    routeId: 'succession',
    space: 'foyer',
    tab: 'proteger',
    family: 'Transmission',
    shortLabel: 'Succession & liquidité',
    fullLabel: 'Droits de succession & liquidité successorale',
    objective: 'Estimer les droits de succession et les besoins de liquidité familiale.',
    inputs: ['famille', 'régime matrimonial', 'actifs', 'passifs', 'donations', 'assurance-vie'],
    calculates: [
      'dévolution',
      'masse civile',
      'assiette fiscale',
      'droits',
      'liquidité nécessaire',
    ],
    outputs: ['droits estimés', 'besoin de liquidité', 'chronologie', 'alertes civiles'],
    upstream: ['filiation', 'regime-matrimonial', 'donations-anterieures', 'actif-passif'],
    next: ['donation-demembrement', 'prevoyance', 'placement'],
    dossierFields: ['foyer', 'famille', 'patrimoine', 'donations', 'succession'],
    legalRefs: [
      'Code civil art. 720 et suivants',
      'CGI art. 669',
      'CGI art. 777',
      'CGI art. 779',
      'CGI art. 990 I',
    ],
    legalRefsStatus: 'complete',
    testScenarios: ['couple marié avec enfants', 'PACS avec testament', 'assurance-vie démembrée'],
    contextPolicy: standalone(['famille', 'patrimoine'], ['foyer', 'patrimoine'], ['donations']),
    lifecycle: 'active',
    visibility: 'simplifie',
    engine: 'src/engine/succession',
  },
  {
    id: 'donation-demembrement',
    space: 'foyer',
    tab: 'proteger',
    family: 'Transmission',
    shortLabel: 'Donation & démembrement',
    fullLabel: 'Donation / donation-partage & démembrement',
    objective: 'Préparer une transmission anticipée en pleine propriété ou en démembrement.',
    inputs: ['donateur', 'bénéficiaires', 'actifs', 'âge usufruitier', 'abattements', 'horizon'],
    calculates: ['valeur usufruit/nue-propriété', 'droits de donation', 'abattements restants'],
    outputs: ['coût donation', 'abattements consommés', 'impact succession futur'],
    upstream: ['succession', 'donations-anterieures', 'sci'],
    next: ['succession', 'prevoyance', 'placement'],
    dossierFields: ['donations', 'patrimoine', 'famille'],
    legalRefs: [],
    legalRefsStatus: 'a-renseigner-avant-codage',
    testScenarios: ['donation simple', 'donation-partage', 'démembrement immobilier'],
    contextPolicy: standalone(['donateur', 'bénéficiaires', 'actifs'], ['patrimoine'], ['famille']),
    lifecycle: 'planned',
    visibility: 'simplifie',
  },
] as const satisfies readonly SimulatorDefinition[];
