import { standalone } from '../contextPolicies';
import type { SimulatorDefinition } from '../types';

export const SOCIETE_SIMULATORS = [
  {
    id: 'organigramme-societe',
    space: 'societe',
    tab: 'comprendre',
    family: 'Société',
    shortLabel: 'Organigramme',
    fullLabel: 'Organigramme société',
    objective: 'Cartographier les sociétés, associés, participations et détentions du dirigeant.',
    inputs: ['sociétés', 'associés', 'participations', 'liens capitalistiques'],
    calculates: ['détention directe', 'détention indirecte', 'contrôle', 'structure de groupe'],
    outputs: ['organigramme', 'participations', 'associés clés'],
    upstream: ['filiation'],
    next: ['valorisation-titres', 'tresorerie-societe'],
    dossierFields: ['societes', 'dirigeant'],
    legalRefs: [],
    legalRefsStatus: 'a-renseigner-avant-codage',
    settingsKeys: [],
    testScenarios: ['société unique', 'holding', 'associés multiples'],
    contextPolicy: standalone(['societes'], ['societes'], ['famille']),
    tags: ['societe', 'audit'],
    lifecycle: 'planned',
    visibility: 'simplifie',
  },
  {
    id: 'valorisation-titres',
    space: 'societe',
    tab: 'comprendre',
    family: 'Société',
    shortLabel: 'Valorisation titres',
    fullLabel: 'Valorisation des titres',
    objective:
      'Évaluer la valeur patrimoniale des titres du dirigeant avant transmission ou cession.',
    inputs: ['bilans', 'résultats', 'trésorerie', 'dettes', 'multiples', 'quote-part'],
    calculates: ['valeur patrimoniale', 'valeur économique', 'quote-part dirigeant'],
    outputs: ['valeur titres', 'valeur dirigeant', 'base de décision'],
    upstream: ['organigramme-societe'],
    next: ['cession-titres', 'pacte-dutreil', 'donation-demembrement'],
    dossierFields: ['societes.valorisation', 'bilans'],
    legalRefs: [],
    legalRefsStatus: 'a-renseigner-avant-codage',
    settingsKeys: [],
    testScenarios: ['holding patrimoniale', 'société opérationnelle', 'quote-part minoritaire'],
    contextPolicy: standalone(['bilans', 'quotePart'], ['societes'], ['bilans']),
    tags: ['societe', 'cession'],
    lifecycle: 'planned',
    visibility: 'expert',
  },
  {
    id: 'projection-comptable',
    space: 'societe',
    tab: 'piloter',
    family: 'Piloter l’exploitation',
    shortLabel: 'Projection comptable',
    fullLabel: 'Projection comptable',
    objective: 'Projeter les flux société avant arbitrage rémunération, dividendes ou trésorerie.',
    inputs: ['résultat', 'trésorerie', 'charges', 'investissements', 'horizon'],
    calculates: ['résultat projeté', 'trésorerie disponible', 'capacité de distribution'],
    outputs: ['projection société', 'cash disponible', 'alertes exploitation'],
    upstream: ['organigramme-societe'],
    next: ['tresorerie-societe', 'remuneration'],
    dossierFields: ['societes.bilans', 'societes.flux'],
    legalRefs: [],
    legalRefsStatus: 'a-renseigner-avant-codage',
    settingsKeys: ['comptables-societes.is'],
    testScenarios: ['résultat stable', 'trésorerie excédentaire', 'investissements lourds'],
    contextPolicy: standalone(['resultat', 'tresorerie'], ['societes'], ['bilans']),
    tags: ['societe', 'fiscalite'],
    lifecycle: 'planned',
    visibility: 'expert',
  },
  {
    id: 'tresorerie-societe',
    routeId: 'tresorerie-societe',
    space: 'societe',
    tab: 'piloter',
    family: 'Piloter l’exploitation',
    shortLabel: 'Trésorerie société',
    fullLabel: 'Trésorerie société',
    objective: 'Projeter une société IS patrimoniale, ses flux, allocations et revenus associés.',
    inputs: ['société', 'associés', 'CCA', 'filiales', 'emprunts', 'allocations', 'revenus'],
    calculates: [
      'trésorerie projetée',
      'flux associés',
      'revenus société',
      'allocation de trésorerie',
    ],
    outputs: ['projection trésorerie', 'revenus distribuables', 'allocation société', 'timeline'],
    upstream: ['organigramme-societe', 'projection-comptable'],
    next: ['remuneration', 'sortie-capitaux', 'holding', 'cession-titres'],
    dossierFields: ['societes', 'bilans', 'dirigeant'],
    legalRefs: ['cgi-38', 'cgi-209', 'cgi-219'],
    legalRefsStatus: 'complete',
    settingsKeys: ['comptables-societes.is', 'comptables-societes.mere-fille-qpfc'],
    testScenarios: ['société avec CCA', 'allocation trésorerie', 'emprunt et filiale'],
    contextPolicy: standalone(['societe', 'tresorerie'], ['societes'], ['bilans']),
    subtypes: ['Placement trésorerie intégré', 'CCA', 'Filiales', 'Emprunts société'],
    tags: ['societe', 'placements', 'investissement'],
    lifecycle: 'active',
    visibility: 'simplifie',
    engine: 'src/domain/tresorerie',
  },
  {
    id: 'remuneration',
    space: 'societe',
    tab: 'piloter',
    family: 'Dirigeant',
    shortLabel: 'Rémunération',
    fullLabel: 'Rémunération dirigeant',
    objective: 'Arbitrer salaire, dividendes et protection sociale du dirigeant.',
    inputs: ['rémunération', 'dividendes', 'charges sociales', 'résultat', 'besoin personnel'],
    calculates: ['net disponible', 'coût société', 'droits sociaux', 'impact IR'],
    outputs: ['arbitrage rémunération', 'net dirigeant', 'coût société'],
    upstream: ['projection-comptable', 'tresorerie-societe'],
    next: ['ir', 'budget', 'epargne-salariale'],
    dossierFields: ['dirigeant', 'societes', 'fiscaliteIR'],
    legalRefs: [],
    legalRefsStatus: 'a-renseigner-avant-codage',
    settingsKeys: [
      'impots.ir.bareme',
      'comptables-societes.dividendes',
      'social-dirigeant.charges-sociales',
      'social-dirigeant.puma-csm',
      'retraite-prevoyance.cotisations-retraite',
      'retraite-prevoyance.validation-retraite-600-smic',
      'placements.epargne-salariale',
    ],
    testScenarios: ['salaire majoritaire', 'dividendes', 'arbitrage mixte'],
    contextPolicy: standalone(['remuneration', 'resultat'], ['societes'], ['fiscaliteIR']),
    tags: ['societe', 'fiscalite'],
    lifecycle: 'planned',
    visibility: 'expert',
  },
  {
    id: 'epargne-salariale',
    routeId: 'epargne-salariale',
    space: 'societe',
    tab: 'piloter',
    family: 'Dirigeant',
    shortLabel: 'Épargne salariale',
    fullLabel: 'Épargne salariale',
    objective: 'Préparer le dimensionnement d’un dispositif d’épargne salariale.',
    inputs: ['effectif', 'rémunérations', 'résultat', 'abondement', 'dirigeant'],
    calculates: ['enveloppe disponible', 'coût société', 'net bénéficiaire', 'économie sociale'],
    outputs: ['enveloppe cible', 'coût estimé', 'bénéficiaires à contrôler'],
    upstream: ['remuneration', 'tresorerie-societe'],
    next: ['retraite', 'placement'],
    dossierFields: ['societes', 'dirigeant', 'salaries'],
    legalRefs: ['code-travail-l3312-1', 'code-travail-l3332-1'],
    legalRefsStatus: 'complete',
    settingsKeys: [],
    testScenarios: ['dirigeant éligible', 'abondement', 'effectif incomplet'],
    contextPolicy: standalone(['effectif', 'rémunérations'], ['societes'], ['dirigeant']),
    tags: ['societe', 'retraite', 'investissement'],
    lifecycle: 'placeholder',
    visibility: 'simplifie',
  },
  {
    id: 'cession-titres',
    space: 'societe',
    tab: 'piloter',
    family: 'Arbitrer',
    shortLabel: 'Cession de titres',
    fullLabel: 'Cession de titres & plus-values mobilières',
    objective: 'Analyser la cession de titres de société et le réemploi possible.',
    inputs: ['valeur titres', 'prix de revient', 'durée détention', 'régime fiscal', 'réemploi'],
    calculates: ['plus-value', 'fiscalité', 'cash net', 'leviers de réemploi'],
    outputs: ['cash net cession', 'fiscalité estimée', 'options holding ou placement'],
    upstream: ['valorisation-titres'],
    next: ['holding', 'placement', 'arbitrage-reemploi'],
    dossierFields: ['societes.valorisation', 'fiscaliteIR'],
    legalRefs: [],
    legalRefsStatus: 'a-renseigner-avant-codage',
    settingsKeys: [
      'comptables-societes.pv-mobilieres',
      'comptables-societes.holding-apport-cession',
      'impots.pfu.part-ir',
      'impots.ps-patrimoine',
    ],
    testScenarios: ['cession simple', 'apport-cession', 'réemploi placement'],
    contextPolicy: standalone(['valeurTitres', 'prixRevient'], ['societes'], ['fiscaliteIR']),
    tags: ['societe', 'cession', 'fiscalite'],
    lifecycle: 'planned',
    visibility: 'simplifie',
  },
  {
    id: 'sortie-capitaux',
    space: 'societe',
    tab: 'piloter',
    family: 'Dirigeant',
    shortLabel: 'Sortie de capitaux',
    fullLabel: 'Sortie de capitaux / CCA',
    objective: 'Comparer les modalités de sortie de cash société vers le dirigeant.',
    inputs: ['trésorerie', 'résultat', 'dividendes', 'rémunération', 'compte courant'],
    calculates: ['cash net dirigeant', 'coût société', 'impact fiscal et social'],
    outputs: ['mode de sortie', 'cash net', 'coût global'],
    upstream: ['tresorerie-societe'],
    next: ['ir', 'budget', 'placement'],
    dossierFields: ['societes', 'dirigeant', 'fiscaliteIR'],
    legalRefs: [],
    legalRefsStatus: 'a-renseigner-avant-codage',
    settingsKeys: [
      'comptables-societes.dividendes',
      'social-dirigeant.charges-sociales',
      'social-dirigeant.puma-csm',
      'impots.pfu.part-ir',
      'impots.ps-patrimoine',
    ],
    testScenarios: ['dividendes', 'remboursement CCA', 'rémunération'],
    contextPolicy: standalone(['tresorerie', 'besoinCash'], ['societes'], ['fiscaliteIR']),
    tags: ['societe', 'cession', 'fiscalite'],
    lifecycle: 'planned',
    visibility: 'expert',
  },
  {
    id: 'holding',
    space: 'societe',
    tab: 'piloter',
    family: 'Arbitrer',
    shortLabel: 'Holding',
    fullLabel: 'Holding / apport-cession',
    objective: 'Qualifier une structuration holding ou un réemploi en société.',
    inputs: ['titres', 'cession', 'réemploi', 'structure cible', 'horizon'],
    calculates: ['cash conservé', 'réemploi', 'contraintes de structure', 'points d’attention'],
    outputs: ['structure cible', 'cash réemployable', 'alertes fiscales'],
    upstream: ['cession-titres', 'tresorerie-societe'],
    next: ['placement', 'pacte-dutreil'],
    dossierFields: ['societes', 'dirigeant'],
    legalRefs: [],
    legalRefsStatus: 'a-renseigner-avant-codage',
    settingsKeys: [
      'comptables-societes.mere-fille-qpfc',
      'comptables-societes.holding-apport-cession',
      'comptables-societes.pv-mobilieres',
    ],
    testScenarios: ['holding animatrice', 'apport-cession', 'réemploi partiel'],
    contextPolicy: standalone(['titres', 'structure'], ['societes'], ['fiscaliteIR']),
    tags: ['societe', 'cession', 'investissement'],
    lifecycle: 'planned',
    visibility: 'expert',
  },
  {
    id: 'pacte-dutreil',
    space: 'societe',
    tab: 'proteger',
    family: 'Transmission entreprise',
    shortLabel: 'Pacte Dutreil',
    fullLabel: 'Pacte Dutreil',
    objective: 'Préparer l’analyse d’une transmission d’entreprise avec engagement Dutreil.',
    inputs: ['société', 'activité', 'engagements', 'bénéficiaires', 'durées'],
    calculates: [
      'éligibilité à contrôler',
      'assiette potentiellement exonérée',
      'conditions bloquantes',
    ],
    outputs: ['checklist Dutreil', 'points bloquants', 'étapes transmission'],
    upstream: ['valorisation-titres', 'organigramme-societe'],
    next: ['donation-demembrement', 'succession', 'prevoyance'],
    dossierFields: ['societes', 'famille', 'transmissionEntreprise'],
    legalRefs: [],
    legalRefsStatus: 'a-renseigner-avant-codage',
    settingsKeys: ['transmission.dmtg-succession', 'transmission.dutreil'],
    testScenarios: ['activité opérationnelle', 'holding', 'enfant repreneur'],
    contextPolicy: standalone(['societe', 'bénéficiaires'], ['societes'], ['famille']),
    tags: ['societe', 'transmission'],
    lifecycle: 'planned',
    visibility: 'expert',
  },
] as const satisfies readonly SimulatorDefinition[];
