insert into public.memento_reference_values (
  key,
  domain,
  subdomain,
  label,
  value_numeric,
  value_text,
  unit,
  year,
  data,
  ref_ids,
  display_order,
  note
) values
  (
    'csm-taux-maximum',
    'social-protection',
    'puma-csm',
    'CSM — taux maximal',
    6.5,
    null,
    '%',
    2026,
    '{"kind":"rate","base":"assiette_csm"}'::jsonb,
    array['urssaf-puma-csm'],
    1000,
    'Taux appliqué à l’assiette CSM avant dégressivité selon les revenus d’activité.'
  ),
  (
    'csm-seuil-revenus-activite-pass',
    'social-protection',
    'puma-csm',
    'CSM — seuil de revenus d’activité',
    20,
    null,
    '%',
    2026,
    '{"kind":"threshold","base":"PASS"}'::jsonb,
    array['urssaf-puma-csm','urssaf-pass-2026'],
    1010,
    'Seuil exprimé en pourcentage du PASS pour apprécier l’assujettissement.'
  ),
  (
    'csm-abattement-assiette-pass',
    'social-protection',
    'puma-csm',
    'CSM — abattement d’assiette',
    50,
    null,
    '%',
    2026,
    '{"kind":"abatement","base":"PASS"}'::jsonb,
    array['urssaf-puma-csm','urssaf-pass-2026'],
    1020,
    'Abattement exprimé en pourcentage du PASS dans la formule CSM.'
  ),
  (
    'csm-plafond-assiette-pass',
    'social-protection',
    'puma-csm',
    'CSM — plafond d’assiette',
    800,
    null,
    '%',
    2026,
    '{"kind":"ceiling","base":"PASS"}'::jsonb,
    array['urssaf-puma-csm','urssaf-pass-2026'],
    1030,
    'Plafond exprimé en pourcentage du PASS.'
  ),
  (
    'agirc-arrco-t1',
    'social-protection',
    'retraite-complementaire',
    'AGIRC-ARRCO — tranche T1',
    null,
    'Employeur 4,72 % · salarié 3,15 % · total 7,87 %',
    null,
    2026,
    '{"employerRate":4.72,"employeeRate":3.15,"totalRate":7.87,"tranche":"T1"}'::jsonb,
    array['agirc-arrco-parametres-2026','urssaf-pass-2026'],
    1100,
    'Cotisation appelée incluant le pourcentage d’appel.'
  ),
  (
    'agirc-arrco-t2',
    'social-protection',
    'retraite-complementaire',
    'AGIRC-ARRCO — tranche T2',
    null,
    'Employeur 12,95 % · salarié 8,64 % · total 21,59 %',
    null,
    2026,
    '{"employerRate":12.95,"employeeRate":8.64,"totalRate":21.59,"tranche":"T2"}'::jsonb,
    array['agirc-arrco-parametres-2026','urssaf-pass-2026'],
    1110,
    'Cotisation appelée incluant le pourcentage d’appel.'
  ),
  (
    'agirc-arrco-ceg-t1',
    'social-protection',
    'retraite-complementaire',
    'CEG — tranche T1',
    null,
    'Employeur 1,29 % · salarié 0,86 % · total 2,15 %',
    null,
    2026,
    '{"employerRate":1.29,"employeeRate":0.86,"totalRate":2.15,"tranche":"T1"}'::jsonb,
    array['agirc-arrco-parametres-2026'],
    1120,
    'Contribution d’équilibre général.'
  ),
  (
    'agirc-arrco-ceg-t2',
    'social-protection',
    'retraite-complementaire',
    'CEG — tranche T2',
    null,
    'Employeur 1,62 % · salarié 1,08 % · total 2,70 %',
    null,
    2026,
    '{"employerRate":1.62,"employeeRate":1.08,"totalRate":2.7,"tranche":"T2"}'::jsonb,
    array['agirc-arrco-parametres-2026'],
    1130,
    'Contribution d’équilibre général.'
  ),
  (
    'agirc-arrco-cet',
    'social-protection',
    'retraite-complementaire',
    'CET — tranches T1 et T2',
    null,
    'Employeur 0,21 % · salarié 0,14 % · total 0,35 %',
    null,
    2026,
    '{"employerRate":0.21,"employeeRate":0.14,"totalRate":0.35,"tranche":"T1+T2"}'::jsonb,
    array['agirc-arrco-parametres-2026'],
    1140,
    'Due si la rémunération dépasse la tranche T1.'
  ),
  (
    'forfait-social-prevoyance',
    'social-protection',
    'epargne-salariale',
    'Forfait social — prévoyance',
    8,
    null,
    '%',
    2026,
    '{"kind":"rate","scope":"prevoyance"}'::jsonb,
    array['urssaf-forfait-social','boss-protection-sociale-complementaire'],
    1200,
    'Taux applicable aux contributions patronales de prévoyance dans le périmètre prévu.'
  ),
  (
    'forfait-social-retraite',
    'social-protection',
    'epargne-salariale',
    'Forfait social — retraite',
    20,
    null,
    '%',
    2026,
    '{"kind":"rate","scope":"retraite"}'::jsonb,
    array['urssaf-forfait-social','boss-protection-sociale-complementaire'],
    1210,
    'Taux de droit commun pour les contributions entrant dans le forfait social.'
  ),
  (
    'pee-abondement-plafond',
    'social-protection',
    'epargne-salariale',
    'PEE — plafond d’abondement',
    3845,
    null,
    'EUR',
    2026,
    '{"kind":"ceiling","product":"pee","base":"PASS"}'::jsonb,
    array['urssaf-plans-epargne-salariale-2026','urssaf-pass-2026'],
    1220,
    'Plafond annuel d’abondement employeur sur un PEE.'
  )
on conflict (key) do update set
  domain = excluded.domain,
  subdomain = excluded.subdomain,
  label = excluded.label,
  value_numeric = excluded.value_numeric,
  value_text = excluded.value_text,
  unit = excluded.unit,
  year = excluded.year,
  data = excluded.data,
  ref_ids = excluded.ref_ids,
  display_order = excluded.display_order,
  note = excluded.note,
  updated_at = now();
