-- PR7 — PP/PM split catalogue
-- Duplicate legacy overrides (old dual IDs) to new split IDs (_pp / _pm)
-- Safe/idempotent: does nothing if source rows are missing; preserves existing split rows.

WITH split_map(old_id, new_id) AS (
  VALUES
    ('assurance_emprunteur', 'assurance_emprunteur_pp'),
    ('assurance_emprunteur', 'assurance_emprunteur_pm'),
    ('contrat_capitalisation', 'contrat_capitalisation_pp'),
    ('contrat_capitalisation', 'contrat_capitalisation_pm'),
    ('cat_compte_a_terme', 'cat_compte_a_terme_pp'),
    ('cat_compte_a_terme', 'cat_compte_a_terme_pm'),
    ('compte_courant_depot', 'compte_courant_depot_pp'),
    ('compte_courant_depot', 'compte_courant_depot_pm'),
    ('csl_compte_sur_livret', 'csl_compte_sur_livret_pp'),
    ('csl_compte_sur_livret', 'csl_compte_sur_livret_pm'),
    ('cto', 'cto_pp'),
    ('cto', 'cto_pm'),
    ('article_83', 'article_83_pp'),
    ('article_83', 'article_83_pm'),
    ('article_39', 'article_39_pp'),
    ('article_39', 'article_39_pm'),
    ('pee', 'pee_pp'),
    ('pee', 'pee_pm'),
    ('percol', 'percol_pp'),
    ('percol', 'percol_pm'),
    ('perco_ancien', 'perco_ancien_pp'),
    ('perco_ancien', 'perco_ancien_pm'),
    ('pero', 'pero_pp'),
    ('pero', 'pero_pm'),
    ('locatif_nu', 'locatif_nu_pp'),
    ('locatif_nu', 'locatif_nu_pm'),
    ('immobilier_garage_parking', 'immobilier_garage_parking_pp'),
    ('immobilier_garage_parking', 'immobilier_garage_parking_pm'),
    ('immobilier_terrain', 'immobilier_terrain_pp'),
    ('immobilier_terrain', 'immobilier_terrain_pm'),
    ('groupement_foncier_agri_viti', 'groupement_foncier_agri_viti_pp'),
    ('groupement_foncier_agri_viti', 'groupement_foncier_agri_viti_pm'),
    ('groupement_foncier_forestier', 'groupement_foncier_forestier_pp'),
    ('groupement_foncier_forestier', 'groupement_foncier_forestier_pm'),
    ('parts_scpi', 'parts_scpi_pp'),
    ('parts_scpi', 'parts_scpi_pm'),
    ('fcpr', 'fcpr_pp'),
    ('fcpr', 'fcpr_pm'),
    ('fcpi', 'fcpi_pp'),
    ('fcpi', 'fcpi_pm'),
    ('fip', 'fip_pp'),
    ('fip', 'fip_pm'),
    ('opci_grand_public', 'opci_grand_public_pp'),
    ('opci_grand_public', 'opci_grand_public_pm'),
    ('actions_cotees', 'actions_cotees_pp'),
    ('actions_cotees', 'actions_cotees_pm'),
    ('actions_preference', 'actions_preference_pp'),
    ('actions_preference', 'actions_preference_pm'),
    ('parts_sociales_cooperatives', 'parts_sociales_cooperatives_pp'),
    ('parts_sociales_cooperatives', 'parts_sociales_cooperatives_pm'),
    ('titres_participatifs', 'titres_participatifs_pp'),
    ('titres_participatifs', 'titres_participatifs_pm'),
    ('droits_bsa_dps', 'droits_bsa_dps_pp'),
    ('droits_bsa_dps', 'droits_bsa_dps_pm'),
    ('actions_non_cotees', 'actions_non_cotees_pp'),
    ('actions_non_cotees', 'actions_non_cotees_pm'),
    ('crowdfunding', 'crowdfunding_pp'),
    ('crowdfunding', 'crowdfunding_pm'),
    ('obligations_non_cotees', 'obligations_non_cotees_pp'),
    ('obligations_non_cotees', 'obligations_non_cotees_pm'),
    ('sofica', 'sofica_pp'),
    ('sofica', 'sofica_pm'),
    ('ir_pme_madelin', 'ir_pme_madelin_pp'),
    ('ir_pme_madelin', 'ir_pme_madelin_pm'),
    ('compte_courant_associe', 'compte_courant_associe_pp'),
    ('compte_courant_associe', 'compte_courant_associe_pm'),
    ('usufruit_nue_propriete', 'usufruit_nue_propriete_pp'),
    ('usufruit_nue_propriete', 'usufruit_nue_propriete_pm'),
    ('crypto_actifs', 'crypto_actifs_pp'),
    ('crypto_actifs', 'crypto_actifs_pm'),
    ('metaux_precieux', 'metaux_precieux_pp'),
    ('metaux_precieux', 'metaux_precieux_pm'),
    ('tontine', 'tontine_pp'),
    ('tontine', 'tontine_pm')
)
INSERT INTO public.base_contrat_overrides (product_id, closed_date, note_admin, updated_at)
SELECT m.new_id, o.closed_date, o.note_admin, o.updated_at
FROM public.base_contrat_overrides o
JOIN split_map m ON m.old_id = o.product_id
ON CONFLICT (product_id) DO NOTHING;
