insert into public.memento_reference_values (
  key,
  domain,
  subdomain,
  label,
  value_numeric,
  value_text,
  unit,
  year,
  data,
  ref_ids,
  display_order,
  note
) values
  (
    'usufruit-viager-moins-21',
    'demembrement',
    'usufruit-viager',
    'Moins de vingt et un ans révolus',
    null,
    'Usufruit 90 % · nue-propriété 10 %',
    null,
    2026,
    '{"kind":"bareme_669_viager","maxExclusiveAge":21,"usufruitRate":90,"bareOwnershipRate":10}'::jsonb,
    array['cgi-669','boi-enr-dmtg-10-40-10-50'],
    2000,
    'Quote-part de la pleine propriété retenue pour la liquidation fiscale.'
  ),
  (
    'usufruit-viager-moins-31',
    'demembrement',
    'usufruit-viager',
    'Moins de trente et un ans révolus',
    null,
    'Usufruit 80 % · nue-propriété 20 %',
    null,
    2026,
    '{"kind":"bareme_669_viager","maxExclusiveAge":31,"usufruitRate":80,"bareOwnershipRate":20}'::jsonb,
    array['cgi-669','boi-enr-dmtg-10-40-10-50'],
    2010,
    'Quote-part de la pleine propriété retenue pour la liquidation fiscale.'
  ),
  (
    'usufruit-viager-moins-41',
    'demembrement',
    'usufruit-viager',
    'Moins de quarante et un ans révolus',
    null,
    'Usufruit 70 % · nue-propriété 30 %',
    null,
    2026,
    '{"kind":"bareme_669_viager","maxExclusiveAge":41,"usufruitRate":70,"bareOwnershipRate":30}'::jsonb,
    array['cgi-669','boi-enr-dmtg-10-40-10-50'],
    2020,
    'Quote-part de la pleine propriété retenue pour la liquidation fiscale.'
  ),
  (
    'usufruit-viager-moins-51',
    'demembrement',
    'usufruit-viager',
    'Moins de cinquante et un ans révolus',
    null,
    'Usufruit 60 % · nue-propriété 40 %',
    null,
    2026,
    '{"kind":"bareme_669_viager","maxExclusiveAge":51,"usufruitRate":60,"bareOwnershipRate":40}'::jsonb,
    array['cgi-669','boi-enr-dmtg-10-40-10-50'],
    2030,
    'Quote-part de la pleine propriété retenue pour la liquidation fiscale.'
  ),
  (
    'usufruit-viager-moins-61',
    'demembrement',
    'usufruit-viager',
    'Moins de soixante et un ans révolus',
    null,
    'Usufruit 50 % · nue-propriété 50 %',
    null,
    2026,
    '{"kind":"bareme_669_viager","maxExclusiveAge":61,"usufruitRate":50,"bareOwnershipRate":50}'::jsonb,
    array['cgi-669','boi-enr-dmtg-10-40-10-50'],
    2040,
    'Quote-part de la pleine propriété retenue pour la liquidation fiscale.'
  ),
  (
    'usufruit-viager-moins-71',
    'demembrement',
    'usufruit-viager',
    'Moins de soixante et onze ans révolus',
    null,
    'Usufruit 40 % · nue-propriété 60 %',
    null,
    2026,
    '{"kind":"bareme_669_viager","maxExclusiveAge":71,"usufruitRate":40,"bareOwnershipRate":60}'::jsonb,
    array['cgi-669','boi-enr-dmtg-10-40-10-50'],
    2050,
    'Quote-part de la pleine propriété retenue pour la liquidation fiscale.'
  ),
  (
    'usufruit-viager-moins-81',
    'demembrement',
    'usufruit-viager',
    'Moins de quatre-vingt-un ans révolus',
    null,
    'Usufruit 30 % · nue-propriété 70 %',
    null,
    2026,
    '{"kind":"bareme_669_viager","maxExclusiveAge":81,"usufruitRate":30,"bareOwnershipRate":70}'::jsonb,
    array['cgi-669','boi-enr-dmtg-10-40-10-50'],
    2060,
    'Quote-part de la pleine propriété retenue pour la liquidation fiscale.'
  ),
  (
    'usufruit-viager-moins-91',
    'demembrement',
    'usufruit-viager',
    'Moins de quatre-vingt-onze ans révolus',
    null,
    'Usufruit 20 % · nue-propriété 80 %',
    null,
    2026,
    '{"kind":"bareme_669_viager","maxExclusiveAge":91,"usufruitRate":20,"bareOwnershipRate":80}'::jsonb,
    array['cgi-669','boi-enr-dmtg-10-40-10-50'],
    2070,
    'Quote-part de la pleine propriété retenue pour la liquidation fiscale.'
  ),
  (
    'usufruit-viager-plus-91',
    'demembrement',
    'usufruit-viager',
    'Plus de quatre-vingt-dix ans révolus',
    null,
    'Usufruit 10 % · nue-propriété 90 %',
    null,
    2026,
    '{"kind":"bareme_669_viager","minAge":91,"usufruitRate":10,"bareOwnershipRate":90}'::jsonb,
    array['cgi-669','boi-enr-dmtg-10-40-10-50'],
    2080,
    'Quote-part de la pleine propriété retenue pour la liquidation fiscale.'
  ),
  (
    'usufruit-temporaire-periode',
    'demembrement',
    'usufruit-temporaire',
    'Usufruit temporaire — période de dix ans',
    23,
    null,
    '%',
    2026,
    '{"kind":"bareme_669_temporaire","periodYears":10}'::jsonb,
    array['cgi-669','boi-enr-dmtg-10-40-10-50'],
    2090,
    'Période retenue sans fraction et sans égard à l’âge de l’usufruitier.'
  )
on conflict (key) do update set
  domain = excluded.domain,
  subdomain = excluded.subdomain,
  label = excluded.label,
  value_numeric = excluded.value_numeric,
  value_text = excluded.value_text,
  unit = excluded.unit,
  year = excluded.year,
  data = excluded.data,
  ref_ids = excluded.ref_ids,
  display_order = excluded.display_order,
  note = excluded.note,
  updated_at = now();
