insert into public.memento_reference_values (
  key,
  domain,
  subdomain,
  label,
  value_numeric,
  value_text,
  unit,
  year,
  data,
  ref_ids,
  display_order,
  note
) values
  (
    'non-residents-ir-premiere-fraction',
    'fiscalite-internationale',
    'non-residents-ir',
    'IR non-résidents — première fraction',
    20,
    null,
    '%',
    2026,
    '{"kind":"minimum_tax_rate","scope":"source_france_income","band":"first"}'::jsonb,
    array['cgi-197-a'],
    3000,
    'Minimum prévu par l’article 197 A.'
  ),
  (
    'non-residents-ir-fraction-superieure',
    'fiscalite-internationale',
    'non-residents-ir',
    'IR non-résidents — fraction supérieure',
    30,
    null,
    '%',
    2026,
    '{"kind":"minimum_tax_rate","scope":"source_france_income","band":"upper"}'::jsonb,
    array['cgi-197-a'],
    3010,
    'Minimum prévu par l’article 197 A.'
  ),
  (
    'non-residents-ir-dom-premiere-fraction',
    'fiscalite-internationale',
    'non-residents-ir',
    'IR non-résidents DOM — première fraction',
    14.4,
    null,
    '%',
    2026,
    '{"kind":"minimum_tax_rate","scope":"dom_source_income","band":"first"}'::jsonb,
    array['cgi-197-a'],
    3020,
    'Minimum prévu par l’article 197 A pour les revenus de source DOM.'
  ),
  (
    'non-residents-ir-dom-fraction-superieure',
    'fiscalite-internationale',
    'non-residents-ir',
    'IR non-résidents DOM — fraction supérieure',
    20,
    null,
    '%',
    2026,
    '{"kind":"minimum_tax_rate","scope":"dom_source_income","band":"upper"}'::jsonb,
    array['cgi-197-a'],
    3030,
    'Minimum prévu par l’article 197 A pour les revenus de source DOM.'
  ),
  (
    'non-residents-ifi-assiette-france',
    'fiscalite-internationale',
    'non-residents-ifi',
    'IFI non-résidents — assiette française',
    null,
    'Actifs immobiliers français et parts à proportion de l’immobilier français taxable',
    null,
    2026,
    '{"kind":"scope","tax":"ifi"}'::jsonb,
    array['cgi-964'],
    3100,
    'Champ d’imposition limité aux actifs français pour les personnes domiciliées hors de France.'
  ),
  (
    'non-residents-dmtg-residence-beneficiaire',
    'fiscalite-internationale',
    'non-residents-transmission',
    'DMTG — bénéficiaire résident fiscal français',
    null,
    'Résidence fiscale française pendant au moins six années au cours des dix années précédentes',
    null,
    2026,
    '{"kind":"territoriality","tax":"dmtg"}'::jsonb,
    array['cgi-750-ter'],
    3200,
    'Critère de territorialité à relire avec les conventions applicables.'
  ),
  (
    'non-residents-assurance-vie-residence-beneficiaire',
    'fiscalite-internationale',
    'non-residents-transmission',
    'Assurance-vie décès — bénéficiaire résident fiscal français',
    null,
    'Résidence fiscale française pendant au moins six années au cours des dix années précédant le décès',
    null,
    2026,
    '{"kind":"territoriality","tax":"assurance_vie_deces"}'::jsonb,
    array['cgi-990-i'],
    3210,
    'Critère d’assujettissement du bénéficiaire à relire avec les conventions applicables.'
  ),
  (
    'non-residents-pvi-personne-physique',
    'fiscalite-internationale',
    'non-residents-immobilier',
    'PVI non-résidents — personne physique',
    19,
    null,
    '%',
    2026,
    '{"kind":"levy_rate","tax":"pvi","taxpayer":"individual"}'::jsonb,
    array['cgi-244-bis-a'],
    3300,
    'Prélèvement sur les plus-values immobilières françaises.'
  ),
  (
    'non-residents-pvi-prelevement-solidarite',
    'fiscalite-internationale',
    'non-residents-immobilier',
    'PVI non-résidents — prélèvement de solidarité',
    7.5,
    null,
    '%',
    2026,
    '{"kind":"solidarity_levy","tax":"pvi"}'::jsonb,
    array['boi-rfpi-pvinr-20-20'],
    3310,
    'Cas d’affiliation à un régime étranger de sécurité sociale selon le BOFiP.'
  )
on conflict (key) do update set
  domain = excluded.domain,
  subdomain = excluded.subdomain,
  label = excluded.label,
  value_numeric = excluded.value_numeric,
  value_text = excluded.value_text,
  unit = excluded.unit,
  year = excluded.year,
  data = excluded.data,
  ref_ids = excluded.ref_ids,
  display_order = excluded.display_order,
  note = excluded.note,
  updated_at = now();
